= 3. IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈


Inversion of Control: 의존 관계 주입(Dependency Injection)이라고도 하며, 어떤 객체가 사용하는 **의존 객체를 직접 만들어 사용하는게 아니라, 주입 받아 사용하는 방법**을 말 함.

스프링 IoC컨테이너

* BeanFactory - https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/BeanFactory.html
* 애플리케이션 컴포넌트의 중앙 저장소
* **빈 설정 소스**로 부터 **빈 정의**를 읽어들이고, **빈을 구성하고 제공**한다.

빈

* 스프링 IoC 컨테이너가 관리 하는 객체.
* 장점
** 의존성 관리
** 스코프
*** 싱글톤: 하나
*** 프로토타입: 매번 다른 객체
** 라이프사이클 인터페이스


ApplicationContext

* BeanFactory
* 메시지 소스 처리 기능 (i18n)
* 이벤트 발행 기능
* 리소스 로딩 기능
* ...





== Bean
* 컨테이너 안에 있는 객체들을 Bean이라고 함.
* 빈들을 담고 있기 때문에 컨테이너라고 함.
* 컨테이너에 있는 빈들을 가져와서 사용할 수 있음.

== 주입 방법
BookService에서 BookRepository를 의존하는데 생성자를 통해 주입 가능.
스프링에서는 여러가지 Dependency Injection 방법들이 있음.


* 스프링 초기에는 XML로 설정하는게 대세
* 구글쥬스가 선보인 애노테이션을 이용한 인젝션 지원.
* @Service, @Repository, @Autowired 같은 것들 사용.
* 빈에 등록되어 있는 객체를 손쉽게 주입받아서 사용할 수 있음.

== BeanFactory 인터페이스
* BeanFactory 인터페이스가 가장 핵심.
* BeanFactory 라이프사이클

[source]
----
Bean factory implementations should support the standard bean lifecycle interfaces as far as possible. The full set of initialization methods and their standard order is:

1. BeanNameAware's setBeanName
2. BeanClassLoaderAware's setBeanClassLoader
3. BeanFactoryAware's setBeanFactory
4. EnvironmentAware's setEnvironment
5. EmbeddedValueResolverAware's setEmbeddedValueResolver
6. ResourceLoaderAware's setResourceLoader (only applicable when running in an application context)
7. ApplicationEventPublisherAware's setApplicationEventPublisher (only applicable when running in an application context)
8. MessageSourceAware's setMessageSource (only applicable when running in an application context)
9. ApplicationContextAware's setApplicationContext (only applicable when running in an application context)
10. ServletContextAware's setServletContext (only applicable when running in a web application context)
11. postProcessBeforeInitialization methods of BeanPostProcessors
12. InitializingBean's afterPropertiesSet
13. a custom init-method definition
14. postProcessAfterInitialization methods of BeanPostProcessors

On shutdown of a bean factory, the following lifecycle methods apply:

1. postProcessBeforeDestruction methods of DestructionAwareBeanPostProcessors
2. DisposableBean's destroy
3. a custom destroy-method definition
----

는 왜 Bean으로 등록했는가?


== ApplicationContext
Interface ApplicationContext
BeanFactory외에 비해 다양한 기능을 가지고 있다.

MessageSource 다국화
ResourceLoader 클래스패스 리소스 불러오기
