= 쿠팡

https://startup.jobs/%EC%BF%A0%ED%8C%A1%EC%9D%98-principal-backend-engineer%EB%93%A4%EC%9D%80-%EB%AC%B4%EC%8A%A8-%EC%9D%BC%EC%9D%84-%ED%95%A0%EA%B9%8C-at-coupang[쿠팡의 Principal Backend Engineer들은 무슨 일을 할까?]

Principal은 '직급'의 표현

Backend 조직의 Principal은 무엇을 하나요?
Individual Contributor로써, 개발에 직접 참여 하고 시니어/쥬니어 개발자의 코드/아키텍쳐 리뷰를 도와줌

----
🚀 이런 분들에게 추천합니다.
🧑🏻‍💻 쿠팡 개발자가 어떻게 일하고 있는지 궁금해 선뜻 지원하지 못하셨던 분들
🧑🏻‍💻 쿠팡으로 입사하게 될 경우 내가 어떤 업무를 하게 될까 확신이 없어 지원을 망설였던 분들
🧑🏻‍💻 쿠팡의 개발 조직은 어떻게 구성되어 있으며 무슨 목표를 가지고 일하는지 찾아보기 어려웠던 분들
🧑🏻‍💻 쿠팡으로 이직하게 될 경우 너무나 다른 환경, 사람, 문화에 적응할 수 있을까 걱정하셨던 분들
🧑🏻‍💻 쿠팡의 코딩 테스트, 불같은 면접 등 어려운 프로세스에 대한 소문을 듣고 지원을 미루셨던 분들
----

Product Engineering
쿠팡 고객의 쇼핑 경험을 책임지고 있는 조직. 회원가입 및 로그인을 하는 순간부터, 쿠팡 홈을 통해 상품을 검색하고, 상세페이지에서 상품을 자세히 살펴보고, 장바구니에 담고, 주문한 후, 상품 리뷰를 작성하기까지의 모든 과정의 서비스를 제공. 이러한 서비스를 확장성 있고 신뢰도 있게 만들기 위한 시스템을 디자인하고 개발하는 것이 Product Engineering 조직의 미션


Product Engineering Eats
쿠팡 이츠 앱에 접속하여 회원가입 및 로그인을 하는 순간부터, 음식을 검색하고, 메뉴를 상세히 살펴보고, 장바구니에 담는 것부터 주문, 상품 리뷸르 작성하는 모든 과정의 서비스를 제공.
대용량 트래픽을 다룰 수 있는 시스템을 디자인하고 제공하고 관리함. 이러한 서비스를 확장성 있고 신뢰도 있게 만들기 위한 시스템을 디자인하고 개발하는 것이 Product Engineering Eats 조직의 미션


Service and Platform Engineering
검색 및 카테고리를 포함한 모든 frontend 페이지에서 쿠팡 사용자 요청을 처리하는 플랫폼을 생성함. 사용자로부터 수백만 건의 요청을 처리한느 플랫폼 팀으로서 우리의 임무는 가용성이 높고 견고하면서도 확장성이 뛰어난 플랫폼을 구축하는 것. Hystrics, Cassandra, Kafka, ES, Spark 등과 같은 다양한 기술과 함께 글로벌 시장에서 선도적인 e-commerce 플랫폼 구축에 기여할 것


