:hardbreaks:
= Brunch - Reactive Spring

Eddy.Kim의 메거진 https://brunch.co.kr/@springboot 의 내용을 공부 하면서 정리합니다.

== 1. 리액티브 프로그래밍

* https://brunch.co.kr/@springboot/152[Project Reactor 1.리액티브 프로그래밍 2019.02.06]

Pivotal에서는 오래전부터 리액티브 프로그래밍을 준비하고 있었음. 프로젝트 이름은 Reactor. Reactor는 Reactive Streams의 구현체. 스피링5 리액티브 프로그래밍의 핵심 라이브러리. Reactor를 먼저 이해하고 Webflux를 도입해야 한다.

=== 1.1 Reactive(리액티브)
리액티브라는 용어는 3가지 의미로 주로 사용됨.
* Reactive Systems (architecture and design)
* Reactive Programming (declarative event-based)
* Functional Reactive Programming (FRP)

자주 사용되는 단어 streaming, lightweight, real-time

뉴욕의 프로그래머에서는
----
"사용자가 해당 소프트웨얼르 사용하기 위해서 어떤 입력을 발생시켰을 때 꾸물거리지 않고 최대한 빠른 시간 내에 응답을 한다는 의미다."
----

MS엑셀의 스프레드시트. 특정 셀의 데이터를 변경하게 되면 해당 셀과 관련된 모든 셀들이 동시에 변경.

=== 1.2. 리액티브 선언문

리액티브의 4가지 속성
* 응답성(responsive)
* 탄력성(resilient)
* 유연성(elastic)
* 메시지 주도(message driven)

https://www.reactivemanifesto.org/ko[리액티브 선언문]

==== 응답성(responsive)
시스템이 가능한 한 즉각적으로 응답하는 것. 신속하고 일관성 있는 응답 시간을 제공하고, 신뢰할 수 있는 상한선을 설정하여 일관된 서비스 품질을 제공. 이러한 일관된 동작은 오류 처리를 단순화하고, 일반 사용자에게 신뢰를 조성하고 새로운 상호 작용을 촉진한다.

==== 탄력성(Resilient)
시스템이 장애에 직면하더라도 응답성을 유지하는 것을 탄력성이 있다고 함. 탄력성이 없는 시스템은 장애가 발생하면, 장애가 전파되고 응답성을 잃게 된다.

==== 유연성(Elastic)
시스템이 작업량이 변화하더라도 응답성을 유지하는 것. 리액티브 시스템은 입력 속도의 변화에 따라 이러한 입력에 할당된 자원을 증가시키거나 감소시키면서 변화에 대응. 시스템에서 경쟁하는 지점이나 중앙 집중적인 병목 현상이 존재하지 않도록 설계하여, 구성 요소를 샤딩하거나 복제하여 입력을 분산시키는 것을 의미. 실시간 성능을 측정하는 도구를 제공하여 응답성 있고 예측 가능한 규모 확장 알고리즘을 지원. 이 시스템은 하드웨어 상품 및 소프트웨어 플랫폼에 비용 효율이 높은 방식으로 유연성을 제공.

==== 메시지 기반(Message Driven)
비동기 프로토콜을 기반으로, 메시지 기반으로 느슨하게 결합한 시스템 아키텍처를 구성. 명시적인 메시지 전달은 시스템에 메시지큐를 생성하고, 모니터링하며 필요시 BackPressure를 적용하여 유연성을 부여한다. 이런 메시지 기반 시스템은 큐 분산 시스템으로 시스템 부하를 막고 안정적인 시스템을 운영할 수 있다.

=== 1.3 리액티브 프로그래밍 vs 리액티브 시스템

=== 1.4 JDK 환경에서의 리액티브 프로그래밍
* RxJava
* Project Reactor
* Spring Framework 5.0
* Ratpack
* Akka

=== 1.5 정리
필자는 작년에 "스프링 리캡 데이"라는 세미나에서 스프링 웹 플럭스에 대해서 강연을 들었음.


== 2. Async VS Non-Blocking
https://brunch.co.kr/@springboot/158[Reactor 2.Async & Non-Blocking]

----
시간이 지나서 다시 읽어보니 적절한 예제가 아닌 것 같다고 함.
----

바리스타가 커피를 만드는 과정으로 설명

리액티브 스트림 구현체
* RxJava
* Reactor


== 3. Reactive Streams
https://brunch.co.kr/@springboot/153[Project Reactor 3. 리액티브 스트림]

2013년 Netflix, Pivotal, Typesafe의 개발자들이 발의해서 처음 만들어졌음. 리액티브 프로그래밍을 위한 명세(specification)이다. 비즈니스 시스템 개발자는 "Reactive Streams"에 정의 된 인터페이스를 구현하면 "리액티브 프로그래밍"을 구현할 수 있다.

이 글에서는 Reactive Streams를 직접 구현하여 구현체를 만든다.

=== 3.1 Reactive Streams Interface
"Reactive Streams" 인터페이스
* Processor
* Publisher
* Subscriber
* Subscription

https://mvnrepository.com/artifact/org.reactivestreams/reactive-streams

글에서는 1.0.2가 최신이었는데 2023.04.08 기준 1.0.4가 최신이다. 1.0.4는 2022.05.26에 배포되었다.

https://github.com/reactive-streams/reactive-streams-jvm/tree/master/api/src/main/java/org/reactivestreams
----
public interface Processor<T, R> extends Subscriber<T>, Publisher<R> {}

public interface Publisher<T> {
    public void subscribe(Subscriber<? super T> s);
}

public interface Subscriber<T> {
    public void onSubscribe(Subscription s);
    public void onNext(T t);
    public void onError(Throwable t);
    public void onComplete();
}

public interface Subscription {
    public void request(long n);
    public void cancel();
}
----

... 클래스 다이어그램 이미지 생략

"Reactive Streams"는 명세를 정의할 뿐, 실제로 구현체를 만들어서 사용해야 함. 기본적인 흐름을 이해하기 위해서 아래 그림 참고

... 이미지 생략

Subscriber 가 Publisher 에게 subscribe 하면 Publisher 가 데이터 또는 시퀀스를 전달하게 된다. 전달하기 전에 Publisher는 Subscribe에 정의된 onSubscribe()를 호출하고, Subscriber는 request(n)를 호출하여 몇개의 데이터를 보내달라고 요청. 이때 Subscription을 사용하는데, Request(n)를 호출하여 데이터 전송 요청을 하게 되면 Publisher 에서는 0에서 N개의 데이터 또는 시퀀스를 Subscriber에 전달하게 된다. 이 과정에서 에러가 발생하면 onError()를 호출하고, 데이터(시퀀스) 전달이 완료가 되면 onComplete()를 호출함. Subscriber가 Publisher에 Request하느 ㄴ과정을 보통 Back-Pressure라고 표현하는데, Push하는 데이터(시퀀스)의 흐름을 제어할 수 있다. Request(1)을 호출하면 1개만 보내도록 요청할 수 있고, Request(MAX)를 호출하면 최대값에 해당하는 데이터를 요청하게 된다. BackPressure를 번역하면, "역압"이라는 단어로 번역할 수 있는데, 그냥 이 글에서는 BackPressure라고 표현.

... 이미지 생략

=== 3.2 Reactive Streams 구현체
위에서 설명했듯이, Reactive Streams는 리액티브 프로그래밍을 위해 정의한 스펙(명세,정의)이다. 실제로 리액티브 프로그래밍을 위해서는, "Reactive Streams"를 구현하는 구현체를 만들어야 한다. 필자가 알고 있는 상식으로 가장 많이 사용되는 구현체 라이브러리는 RxJava. 그 외에 필자가 알고 있는 "Reactive Streams"의 구현체는 아래와 같음.
* RxJava 1.x or RxJava 2.x
* Project Reactor
* Vert.x
* Akka Streams
* Slick

참고로, "Ractive Streams" 스펙은 서로 호환된다고 한다. (필자가 검증을 하지는 않았음.)

기회가 된다면 RxJava를 공부해보고 싶지만, 이 글에서는 Reactor를 자세히 다룰 예정

=== 3.3 Reactive Streams 샘플 구현

Reactive Streams를 구현하여, 간단한 리액티브 프로그램을 만들어보자.

==== 디펜던시

스프링 부트 2.0.7, Java Gradle 환경에서 개발
* org.reactivestreams:reactive-streams:1.0.2
* org.springframework.boot:spring-boot-starter-web

org.springframework.boot:spring-boot-starter-test

==== 클래스 다이어그램

Publisher, Subscriber, Subscription 의 구현체 만들기.

* EddyPublisher
* EddySubscriber
* EddySubscription

... 이미지 생략

==== Publisher

Publisher 인터페이스는 다음과 같이 단 하나의 메서드를 정의함
* subscribe

Publisher 를 구현하는 EddyPublisher 클래스는 subscribe 메서드를 구현해야 함. subscribe메서드는 Subscriber 객체를 매개변수로 받고, 매개변수로 받은 subscriber의 onSubscriber() 메서드를 실행함.





=== Publisher
* subscribe

Flux, Mono는 Publisher의 구현체


=== Subscriber
* onSubscribe
* onNext
* onError
* onComplete

=== Subscription
* request
* cancel


== 4. Project Reactor Flux, Mono
* https://brunch.co.kr/@springboot/154[Project Reactor 4. Flux, Mono 2019.02.16]

reactor 3는 Java 8 이상

스프링 webflux 환경인 경우 reactor-core가 포함되어 있음.

Flux, Mono는 Publisher의 구현체.

* Flux: 0-N개의 데이터 전달
* Mono: 0-1 개의 데이터 전달

=== 4.2 Publisher 구현체, Flux와 Mono
==== 0-N개의 데이터를 전달하는 Flux
이벤트
* onNext: 하나의 데이터를 전달할 때마다 발생
* onComplete: 모든 데이터의 전달 처리가 완료 되면 발생
* onError: 데이터를 전달하는 과정에서 오류가 발생 하면 발생

==== 0-1개의 데이터를 전달하는 Mono

=== 4.3 Flux를 생성하는 방법
* just
* range
* fromArray, fromIterable, fromStream
* empty

==== just


== 5. Project Reactor Subscriber

== 6. Project Reactor Data Processing

== 7. Project Reactor Create, Generator

== 8. 미정
