:hardbreaks:

= 나는 프로그래머다


== Episode 18: 해외취업 특집 1,2부 – 채민철님, 김용욱님과 함께

임작가, 정개발, 데니스

http://ww25.iamprogrammer.io/2015/12/07/episode-18-%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85-%ED%8A%B9%EC%A7%91-1%EB%B6%80-%EC%B1%84%EB%AF%BC%EC%B2%A0%EB%8B%98-%EA%B9%80%EC%9A%A9%EC%9A%B1%EB%8B%98%EA%B3%BC-%ED%95%A8%EA%BB%98

https://iamprogrammersite.wordpress.com/2015/12/07/episode-18-%ed%95%b4%ec%99%b8%ec%b7%a8%ec%97%85-%ed%8a%b9%ec%a7%91-1%eb%b6%80-%ec%b1%84%eb%af%bc%ec%b2%a0%eb%8b%98-%ea%b9%80%ec%9a%a9%ec%9a%b1%eb%8b%98%ea%b3%bc-%ed%95%a8%ea%bb%98/[Episode 18: 해외취업 특집 1부 – 채민철님, 김용욱님과 함께]

https://iamprogrammersite.wordpress.com/2015/12/14/episode-18-%ed%95%b4%ec%99%b8%ec%b7%a8%ec%97%85-%ed%8a%b9%ec%a7%91-2%eb%b6%80-%ec%b1%84%eb%af%bc%ec%b2%a0%eb%8b%98-%ea%b9%80%ec%9a%a9%ec%9a%b1%eb%8b%98%ea%b3%bc-%ed%95%a8%ea%bb%98/[Episode 18: 해외취업 특집 2부 – 채민철님, 김용욱님과 함께]


=== 채민철님
개발자 15년, 미국온지 3년 넘었음
경험 공유하고자 페이스북 그룹 만들었음
프론트엔드 엔지니어
웹프로그래머, 소프트웨어 아키텍트 하다가 프론트엔드 넘어 온지 7년

실리콘벨리 써니베일 시티
애플 헤드쿼터랑 걸어서 5분 정도

비자가 가장 중요
인터뷰 보다가 된 회사에 들어간거
스타트업. 5년 정도 된 스타트업
파이낸스 관련 빅데이터 회사
직원은 150명 정도 됨
유일한 한국인

개발자해외취업

한국 SI

엔지니어 좋아해서 일하다가 나이가 있다 보니 관리자로 넘어가야 되는 시기
프로젝트 리드하고 있었고 정치, 신경전 스트레스 받았음.
개발 외 업무가 많이 생겨서 스트레스
육아 휴직 내고 미국으로 왔음. 6월 말. 2012년.
마침 법이 바껴서 아기가 취학전이면 휴직을 낼수 있었음.
아마 첫 육아휴직자였을 듯.

당시에는 학생 비자로 왔음. 영어로 말해본 적도 없었고. 어학 연수로 왔음.
정보를 구하려고 working US 같은데 글을 올려봤음. 네거티브한 답변이 달리고. 비꼬는 말도 있고. 한국 사람들이 이용하는 사이트. 전혀 도움이 안되었음.
저처럼 잡을 구한 사람을 찾기 어려움. 여기서 학교를 나왔거나 주재원, 한국에서 미국 회사 일하다가 넘어오거나. 저처럼 한국에서 넘어와서 잡 구한 케이스는 없었음. 정보 찾기가 힘들었음. 이력서 내면 리쿠르터도 처음.
6개월 어학 연수 하고 1월 말 부터 인터뷰 봐서 한달만에 잡을 구하긴 했음. 비자 상태 때문에 30군데 면접 보고 진행 되는게 5군데.
모르고 와서 운이 좋았음.

여기도 한국 개발자들 있으니 인터뷰. 비자 어떻게. 준비해서. 당시 프론트엔드가 인원이 부족했었음. 그래서 그나마 가능성이 있었음.

나같은 사례도 없고 해서 정보 공유 하려고 페이스북 그룹을 만들었음.

링크드인에 프로필 올렸음. 리쿠르팅 회사들 많음. 미국에서는 2년 정도 일해도 오래 일한 거. 자기들 키워드에 맞는 사람 찾으면 연락이 옴. 그렇게 해서 시작이 된 거.

6개월 어학 연수 하고 영어로 인터뷰 어려움?
한국 사람들이 말을 잘 못하니 1월 초에 최초 인터뷰를 시작 했는데 하나도 안들림. 리쿠르터하고 이야기 하는데. 쇼크를 먹고. 3주 정도를 영어 연습하고 다시 시작. 그래도 똑 같았음. 4월 1일에 비자를 넣어야 했기 때문에 3월에는 취업을 해야 되고. 2월 안에는 잡 오퍼를 받아야 되는 상황. 더 이상 물러설데가 없었음. 2주 정도 하니까 리쿠르터들 대하는 패턴이 비슷하다 보니 점점 적응. 2,3주 지나고 부터는 어느 정도는 리쿠르터와 대화가 됨.

상대방이 못알아 들었을 때 좌절 어떻게?
궁지에 몰리면 하게 되어 있음. 살기 위해서 어쩔 수 없이 하게 됨. 발음에 크게 신경 안써도 됨. 무조건 뱉는게 중요. 못알아 들으면 묻게 되어 있음. 그 때 또박또박 이야기 하면 됨. 폰 스크린 인터뷰. 원하는 백그라운드 가지고 있는지, 기본적인 소통 능력이 있는지 체크. 실리콘벨리 인터네셔널 많기 때문에 다들 발음 틀림. 러시아, 중국 등. 자기 의견을 똑바로 말하는게 더 중요.

워크 퍼밋 나몰라라 하는 경우 보신적 있는지?
중요한 건 엔지니어로서의 경쟁력.

어떤 기술을 준비?
JavaScript, SenchaTouch, YUI, jquery, 회사 프레임워크를 만들었었던 경험.
첫번째 인터뷰 본 회사가 오퍼 주려고 했는데 외국 사람 뽑는 경험이 부족. 미국 비자 신청 4월 1일. 일을 10월 부터. 회사에서 그걸 몰랐음. 경력자를 뽑은건 일이 급해서 뽑았는데 7개월을 기다려야 되었음. 안되겠다고 취소했음.
뽑아놓고 변호사랑 이야기해보니 안되니 다른 사람 뽑음.

다른 회사는 그 문제 어떻게 해결?
워킹 비자 없어서 신청해야 되는 단계에서 리쿠르터와 이야기 하면서 95%는 진행이 안되는데. 5% 확률에서 어떤 케이스가 있냐면. 인원을 구할때 장기적으로 구함. 프론트엔드 5명 확충 계획으로 장기적으로 구하는 곳이 있음. 장기적으로 구하니까 뽑을 거야. 미국회사들 특이한 부분은 원하는 candidate가 아니면 안뽑고 비워두고 기다림. 5명 뽑는 장기적 계획이 있었던 회사. 6월 말에 와서 10월 부터 일함. 학생 비자로 와서 워크 퍼밋으로 일하게 된 거.

역촋. 비자가 안나오면 리모트로 일하다가 전환.

큰 회사들은 한국 지사가 있거나 그러면... (없어도 가능?)

일주일에 하루 정도는 집에서 일함. 리모트로 일하는 것은 일상적인 거. 저희 팀장도 러시아에서 한달.
저도 한국 가서 1주는 리모트로 일하고 돌아옴. 그런 문화.

자제분들 나이가?
첫째 3살, 둘째 2살.
한국에 있을 때는 맞벌이라 아이들과 함께 하기 어려웠는데 한동안 아이들과 함께 해서 좋았음.
교육은 처음부터 미국 시스템으로 해서 문제 없었음.
학교 가면 미국사람이 적음. 90%는 인터네셔널.
어떻게 보면 미국 사람이 소수 민족. 엔지니터들 80% 이상이 인터네셔널.

2부.

미국 생활 적응하면서 어려웠던 에피소드?
일적인 측면은 너무 좋음. 처음에 적응하는 부분. 애자일을 쓰는데. 시간당 관리를 하는데. 한국에서 일하는 습성이 있으니. 일정에 쫓기니. SI는 특히 일정 맞추기 급급. 품질보다는 일정. 그런데 미국같은 경우에는 일정보다는 품질이 더 중요시됨. 그 부분 적응하는게 힘들었음. 저 혼자 일정을 빡빡하게 짜는거. 애자일이니까 엄청 열심히 하게 됨. 소통이 많이 안되니 열심히 일을 했음. 그런데 품질이 생각보다 그들에 비해서 좋지 않았음. 빨리 나가긴 하는데. 그런 문제가 있었음. 지금은 일정을 넉넉하게 잡고 좀 더 내가 만족하는 수준으로 코딩 할 수 있는게 좋음. 근무 자체도 일 중심이기 때문에 한국보다 훨씬 나은거 같고. 힘든거는 소통문제. 1년 정도 다니니까 겨우 이제 몇 마디 할 수 있을 정도. 들리고. 2년 넘었는데 하고 싶은 이야기 할 수 있는 정도. 소통이 가장 큰 문제인 거 같음. 나머지는 좋음.

미국으로 옮겨가는 과정 자체는 권하는 방법은 아님. 몰랐기 때문에 그랬고 알았으면 이러지는 않았을 듯.

몬스터, 다이스는 거의 죽었고
90% 이상은 링크드인

실력 위주.
해고가 쉬움.
첫번째 해고 봤던게 빅데이터 팀장. 고객지원을 잘 안해줘서. 아침에 농담하며 회의 하다가 점심 먹고 짐싸들고 갔음.
올해 초에 레이오프. 30%를 잘랐음. 하루 아침에. 150명중 50명 정도가 잘림.
경쟁력 있는 실력이 없으면 잘리게 되어 있음.
워킹비자가 H1. 워킹비자 있다가 잘리면 15일 이내에 트랜스퍼 못하면 돌아가야 됨.

미국에서 석사
CPT (파트타임잡), OPT (풀타임잡)
OPT, CPT제도를 활용해서 취업을 할 수 있음.
석사로 단기에 1년만에 끝낼 수 있음.
한국에서 토플, 석사 공부 조금 해두고, 미국에서 1년안에 석사 따는걸 목표로 해서 진행. 6개월 넘어서면 졸업반. OPT를 사용해서 바로 취업.
미국에서 소요한 시간이 6,7개월.
한국에서 준비해서 미국와서 석사 압축해서. 힘들게 공부해서 1년안에 끝내고. 취업한 상태에서. OPT 2년 까지 연장 가능. 취업 비자로 트랜스퍼. 이게 best way.

좋은 대학을 갈 필요는 없는 거. 경력이 있기 때문에 커버가 되는거. 석사는 단순히 비자의 불편함을 해소하기 위한 방법. 석사중에 제일 쉬운 석사를 찾는거.

6월 말에 와서 15개월을 놀고 있었음. 석사를 알았다면 석사를 했을듯.

왜 해외취업인가?
한국에서는 40대가 넘으면 관리자. 엔지니어 일을 놓아야 됨. 개발을 더 이상 못하게 되는 상황. 그게 가장 큰 거 였고. 미국은 저 보다 나이 많은 50대 넘은 시니어 엔지니어도 많음.
여기는 그런거에 크게 신경 안쓰고 자기 하고 싶은거. 급여도 한국보다 훨씬 많이 주고. 한국 대기업 때 보다 많이 받음. 생활비가 높긴 하지만. 업무 시간도 한국 처럼 야근이 없고. 야근 한다는거 자체가 단어 자체를 안씀. 급한 일이 있으면 1년에 몇 번 정도 있긴 하지만. 자기하고 가족하고 같이 할 수 있는 개인시간이 많다는 거.

그런게 만족된다면 한국이 더 좋음.

한국은 학연 지연 중요한데 매니지먼트 올라가면 그런게 영향.
순수하게 실력으로 경쟁하는거.

한국 회사 다닐 때 회식을 못가면 눈치 봐야 되고 심적으로 압박. 직급이 올라갈수록 더 심해지고. 저희 여자 임원 같은 경우에는 자기는 애기를 데리고 출근했다. 새벽 몇시까지 고객과 술 먹는거 자랑스럽게 이야기.

그룹의 목적은 시행착오를 줄여주는거. 미국 취업 하려면 어떤걸 준비. 코딩인터뷰 스터디도 함께 진행하고 있음. 한국과 다르게 미국은 스타트업이 활성화 되어 있음.

최소한 2년은 언어 준비. 이력서도 중요. 충분히 경쟁력이 있도록 잘 만들기. 취업의 베스트웨이는 석사통해서하는거. 4월 1일에 비자 접수 되니 1월에 들어와서 잡을 구하는 방법. 브로커 같은 우회 방법은 피해를 볼 수 있으니 철저히 준비해서 성공할 수 있도록.




=== 김용욱님. 역촋

...

