:hardbreaks:

= 데이터 정규화



== 참고
데이터 정규화가 뭔지 설명해보세요 (개발면접타임)
https://www.youtube.com/watch?v=Y1FbowQRcmI

제1정규화
한 칸엔 하나의 데이터만

제2정규화
현재 테이블의 주제와 관련없는 컬럼을 다른 테이블로
단점은 다른 테이블 같이 조회해야 되어서 조금 귀찮아짐
비관계형 DB들은 정규화 안하는 경우가 많음

partial dependency를 제거한 테이블

Composite primary key

제3정규화
일반 컬럼에만 종속된 컬럼은 다른 테이블로 빼기

[10분 테코톡] 짱구의 정규화 2022.11.03
https://www.youtube.com/watch?v=DHyYQod48pk

member, study, ...

정보의 중복
한 릴레이션에 여러 엔티티의 애트리뷰트들이 존재하면 정보가 중복 저장된다
저장 공간 낭비
갱신 이상 발생

갱신 이상
삽입 이상 - 불필요한 정보를 함께 저장하지 않고는 어떤 정보를 저장하는 것이 불가능
삭제 이상 - 유용한 정보를 함께 삭제하지 않고는 어떤 정보를 삭제하는 것이 불가능
수정 이상 - 반복된 데이터 중에 일부만 수정하면 데이터의 불일치가 발생

정규화란?
관계형 데이터베이스 설계 시 중복과 갱신 이상을 최소화하기 위해서 데이터를 구조화하는 작업

릴레이션 분해
정규화가 진행되면 기존의 릴레이션이 분해된다 -> 분해된 릴레이션들은 무손실 조인을 보장해야 한다

함수적 종속성
정규화가 진행되면 기존의 릴레이션이 분해된다 -> 분해된 릴레이션들은 함수적 종속성을 보존해야 한다

애트리뷰트 X의 값이 애트리뷰트 Y의 값을 유일하게 결정한다면 Y가 X에 함수적으로 종속한다고 말한다

완전 함수적 종속성
어떤 애트리뷰트가 기본키에 대해 완전히 종속적일 때를 말한다

이행 함수적 종속성
릴레이션에서 X, Y, Z라는 3개의 속성이 있을 때 X-Y, Y-Z 이란 종속 관계가 있을 경우. X-Z가 성립될 때를 말한다

정규화 과정
제1정규형 -> 제2정규형 -> 제3정규형 -> 보이스 코드 정규형 -> 제4정규형 -> 제5정규형 -> 제6정규형

비정규화 릴레이션

제1정규형
릴레이션의 모든 애트리뷰트가 원자값만을 갖는다 -> 반복 그룹이 나타나지 않아야 한다.
하나의 튜플로 표현
새로운 릴레이션으로 분리

제2정규형
1) 릴레이션이 제1정규형을 만족하고
2) 기본키가 아닌 모든 애트리뷰트가 기본키에 완전 함수 종속되도록 릴레이션을 분해한다
->
기본키가 두 개 이상의 애트리뷰트로 구성되었을 경우에만 제2정규형을 만족하는가를 고려할 필요가 있다

상품명은 부분 함수 종속된다

주문, 주문상품, 상품

제3정규형
1) 릴레이션이 제2 정규형을 만족하고
2) 기본키가 아닌 모든 애트리뷰트가 기본키에 이행적 함수 종속되지 않도록 릴레이션을 분해한다

회원 분리

정규화 장점
* 데이터 구조의 안정성 유지
* 중복 값 & 널 값이 줄어든다
* 이상 현상 제거
* 저장 공간 최소화

정규화 단점
* 릴레이션의 분해로 인해 릴레이션 간의 (JOIN) 연산이 많아진다.

참고자료
* ORACLE을 기반으로 하는 데이터베이스 배움터
* 데이터아키텍처 전문가가 가이드
* Head First SQL
* https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description
* https://ko.wikipedia.org/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4_%EC%A0%95%EA%B7%9C%ED%99%94


