:hardbreaks:
= Java Generics


== References

https://www.youtube.com/watch?v=QcXLiwZPnJQ[자바의 정석 - 기초편 ch12-1 지네릭스란? 2020.09.01]

컴파일시 타입을 체크해 주는 기능(compile-time type check) - JDK1.5

[source,java]
----
// T객체만 저장할 수 있는 ArrayList를 생성
ArrayList<Tv> tvList = new ArrayList<Tv>();

tvList.add(new Tv()); // OK
tvList.add(new Audio()); // 컴파일 에러. Tv 외에 다른 타입은 저장 불가
----

[source,java]
----
ArrayList list = new ArrayList();
list.add(10); // list.add(new Integer(10)); 오토박싱
list.add(20);
list.add("30"); // 컴파일 에러가 발생하지 않음

Integer i = (Integer)list.get(2);
// 컴파일 에러가 발생하지 않지만, 실행시 에러가 발생함. ClassCastException 형변환에러
// 컴파일러의 한계

System.out.println(list);
----

컴파일 에러 > 실행시 에러

컴파일 때 잡아 낼 수 있는 것이 더 좋음

[source,java]
----
ArrayList<Integer> list = new ArrayList<Integer>();

...
// list.add("30"); // 컴파일 에러 발생
list.add(30); // 타입 체크가 강화됨. 지네릭스 덕분에

Integer i = list.get(2); // 형변환 생략 가능
----


여러종류 사용하려면 Object 사용
[source,java]
----
ArrayList<Object> list = new ArrayList<Object>();
----

여러종류의 객체를 사용할 수 있음

JDK 1.5 이전에는 <> 생략하면 Object 였지만 지네릭스 도입이후에는 <Object> 라고 써줘야 됨.
에러가 나지는 않는데 좋은 코드가 아님

ArrayList.class

옛날에는 일반클래스
public class ArrayList extends AbstractList

지네릭스 도입 이후에는
public class ArrayList<E> extends AbstractList<E>

12-1 지네릭스(Generics)란?
- 컴파일시 타입을 체크해 주는 기능(compile-time type check) - JDK1.5
- 객체의 타입 안정성을 높이고 형변환의 번거로움을 줄여줌

[source,java]
----
ArrayList tvList = new ArrayList();
tvList.add(new Tv());
Tv t = (Tv)tvList.get(0);
----

[source,java]
----
ArrayList<Tv> tvList = new ArrayList<Tv>();
tvList.add(new Tv());
Tv t = tvList.get(0); // 형변환 불필요
----

컴파일러에 타입을 제공해 줘서 컴파일시 타입 체크 강화

지네릭스의 장점
1. 타입 안정성을 제공
2. 타입체크와 형변환을 생략할 수 있으므로 코드가 간결해 진다.

ClassCastException 형변환 에러 예외

Exception 클래스와 RuntimeException 클래스 중심의 상속계층도

예외의 상속계층도

Exception Runtime error 실행중 발생에러
- IOException
- ClassNotFoundException
- ...
- RuntimeException 프로그래머 실수로 발생에러
  - ArithmeticException
  - ClassCastException 형변환에러
  - NullPointerException 참조변수 null
  - ...
  - IndexOutOfBoundsException 배열범위 벗어나느것

compile time 에러가 나음. 실행하기 전에 수정할 수 있음

문서 작성하다가 에러나면 문서 저장도 못하고 날려버릴 수 있음

String str = null;
String str = ""; // 빈문자열. 이게 더 좋은 코드
str.length(); // null 이면 NullPointerException 발생. 빈 문자열이면 0이 되고 NPE가 발생하지는 않음

[source,java]
----
Object[] objARr = null;
Object[] objArr = new Object[0]; // 빈 배열. 길이가 0인 배열. 이게 더 좋은 코드
// = Object[] objArr = {};
----

