:hardbreaks:
= Dockerize

이슈: https://github.com/junho85/garden8/issues/4

일단 도커허브에 private 으로 만들어서 사용한다.
https://hub.docker.com/

private 으로 생성하는 이유는 slack key 정보 등이 들어가기 때문이다.

이 부분은 run 할 때 설정을 넘길 수 있도록 하던지, 개인 docker registry를 구축해서 사용해야겠다.

설정파일을 config volume을 생성해서 거기것을 참조하도록 하는게 좋을거 같다.

공개 이미지로 만들면 도커허브에서도 public 으로 이미지 올리면 된다.

Dockerfile을 생성한다. chatgpt 보고 Dockerize 하는 방법 알려 달랬더니 잘 알려 준다. 조금만 고쳐쓰니 완성.

[source,dockerfile]
----
# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt ./

# Install the application dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . .

# Specify the command to run when the container starts
CMD [ "python", "./manage.py", "runserver", "0.0.0.0:8000" ]
----

이미지를 빌드하는 명령어는 다음과 같다.
[source,shell]
----
$ docker build . -f Dockerfile --tag garden8:20230212_1
----

pycharm에서 이미지 빌드와 실행을 동시에 할 수도 있고

https://www.jetbrains.com/help/pycharm/docker.html#build-image

이미 생성한 이미지로 실행할 수도 있었다.

https://www.jetbrains.com/help/pycharm/docker.html#run_image

실행이 잘 안되어서 커맨드로 했었기도 한데

[source,shell]
----
$ docker run --rm -it --name garden8 -p 127.0.0.1:8000:8000 garden8:20230212_1
----

pycharm을 껐다 켜니까 잘 된다.

== config 파일 분리
설정 파일을 분리하기 위해 기존 attendance에 있던 config.ini, users.yaml 파일을 attendance/config 로 옮김
이제 attendance/config 는 -v 옵션을 이용해서 마운트 해서 사용하도록 함

[source,shell]
----
$ docker run --rm -it -v config/attendance:attendance/config --name garden8 -p 127.0.0.1:8000:8000 garden8:20230212_1
----

설정 파일은 기본적으로 `/config/attendance` 경로를 사용하도록 하고 환경변수로 `GARDEN_CONFIG_DIR` 을 설정한 경우 해당 설정을 따르도록 한다.

만약 PyCharm에서 기본 환경 변수 값을 설정하려면 Run > Edit Configurations... > Edit configuration templates... 에 가서 `;GARDEN_CONFIG_DIR=./config/attendance` 설정을 추가해 주면 다른 run 을 생성할 때 마다 기본환경변수로 세팅되게 된다.

다른 이야기지만 Working directory도 template에 설정해 두면 좋다. 예를 들어 cli_collect.py 같은 파일을 실행시킬 때 working directory가 attendance 로 되면 garden 등의 파일을 불러오기 불편하기에 프로젝트 디렉터리를 working 디렉터리로 지정해 두는 것이 좋다.

== docker hub에 이미지 push

로컬 tag를 docker hub 경로 붙여서 새로 따고 push

[source,shell]
----
$ docker tag garden8:20230212_2 junho85/garden8:20230212_2
$ docker push junho85/garden8:20230212_2
----

문제는 M1 맥북에서 빌드 하니 OS/ARCH가 linux/arm64/v8 로 나오는데 호스팅 서버와 맞을까?

linux/amd64 를 지원하도록 빌드하고 push

[source,shell]
----
$ docker buildx build --platform linux/amd64,linux/arm64 -t junho85/garden8:20230212_2 --push .
----


== 설정파일 volumes 설정
TODO

== 참고
https://www.docker.com/blog/how-to-dockerize-your-python-applications/[How to “Dockerize” Your Python Applications]
