:hardbreaks:

= AI - Artificial Intelligence

인공지능

http://www.caif.or.kr/

== 2022 충청권 인공지능 주간

2022.10.11 화

요즘 미쳐버린 생성 AI 시대 총정리와 꼭 필요한 역량 2022.11.04
https://www.youtube.com/watch?v=ka0qKUP8Ln8

조코딩 채널에 올라온 영상

인공지능(AI)의 개념
인간의 지능을 모방

인공지능(AI) - 넓은 의미로 규칙 기반 포함. 모든 자동화
머신러닝 - 데이터 기반 스스로 기계가 학습
딥러닝 - "인공 신경망" 기반으로 학습

포함 관계
인공지능 > 머신러닝 > 딥러닝

데이터를 통해 패턴을 배운다.

학습 알고리즘
지도학습, 비지도학습, 강화학습

빅데이터 - (학습알고리즘) -> 모델 - (새로운 데이터) -> 예측/판단/생성

최적화된 함수 찾기. 가장 가까운 함수를 찾는 것

w:weight(가중치)
b:bias

예측/판단은 어떻게 하냐.

인공지능 배울 때 Boston Housing Price 예제가 유명

머신러닝과 딥러닝 차이
머신러닝: 모든 학습 알고리즘을 포괄
딥러닝: 인공적인 신경망 기반으로 학습

학습 방법의 차이이고 모델은 같음.

뇌는 뉴런으로 구성되어 있음. 이것과 유사하게 퍼셉트론이라는 개념을 만들어서 여러개의 층을 만들어서 학습. 각각의 파라미터를 두고 조정.

딥러닝을 적용하니 머신러닝 대비 엄청난 성과

2012년 이후에는 모델들이 딥러닝 기반으로 나오게 됨

그래프 출처: 엄청난 데이터+딥러닝 기술 한국, 의료영상 진단의 성지 될 수 있다 2015년 10월
https://dbr.donga.com/article/view/1101/article_no/7251

2. 최신 AI와 미래

GPT-3 (2020) OpenAI

인풋 대비 아웃풋이 엄청난 결과 창출

텍스트 -> GPT-3 -> 텍스트

소설 쓰기, 이메일 답장, 가계부 완성




---

🎬Stable Diffusion 완벽 가이드 영상
https://youtu.be/emObTucGMOA

🎬Dreambooth 파인튜닝 하는 방법
https://youtu.be/vL1t2UcE998

🎬인공지능 만들어보기
https://youtu.be/USQGTW34lO8

웹개발 5주 완성
jocoding.net

목차
00:00 미리보기
00:08 목차 소개
00:39 인공지능의 개념
01:13 인공지능, 머신러닝, 딥러닝 차이
02:05 인공지능 모델을 만드는 방법
02:42 인공지능의 개념 한장 정리
03:36 기계가 학습하는 방법
07:29 딥러닝이란?
08:48 최신 AI와 미래
08:55 최초의 초거대 AI 모델 GPT-3의 등장
10:15 코딩해주는 인공지능의 등장
11:17 한국어 초거대 AI
12:15 text2img
14:14 Stable Diffusion과 AI의 대중화
16:08 지금도 쏟아지는 파인튜닝된 모델
16:14 영상, 오디오, 3D모델 등 생성하는 인공지능 등장
16:57 현재와 미래의 작업 방법
18:10 생각을 텍스트로 바꿔주는 기술
18:42 앞으로 중요한 역량
20:10 Q&A



== History

=== 2021년 6월 AI가 반도체 설계
구글이 일부 공개한 소름돋는 사진, 인공지능이 스스로 진화해버린 역사적인 순간 2021.07.11
https://www.youtube.com/watch?v=_rs4CK5-ss0

2021년 6월 구글과 스탠포드 연구진. AI가 6시간만에 반도체 설계



=== 2016년 3월 이세돌vs알파고 Google DeepMind Challenge Match
구글 딥마인드사의 바둑 인공지능 프로그램인 알파고와 한국의 프로 기사인 이세돌 九단과의 바둑 대국.

기간: 2016년 3월 9일 ~ 3월 15일

5회 대국이 있었고 4회만 이세돌이 이기고 나머지는 알파고가 이겼음


