:hardbreaks:

= AI - Artificial Intelligence

인공지능

http://www.caif.or.kr/

== 2022 충청권 인공지능 주간

2022.10.11 화

요즘 미쳐버린 생성 AI 시대 총정리와 꼭 필요한 역량 2022.11.04
https://www.youtube.com/watch?v=ka0qKUP8Ln8

조코딩 채널에 올라온 영상

인공지능(AI)의 개념
인간의 지능을 모방

인공지능. 어떤것이 개고 어떤것이 고양이고를 구분. 입력이 있으면 출력을 하는 것. 수학에서의 함수의 개념.

* 인공지능(AI) - 넓은 의미로 규칙 기반 포함. 모든 자동화
* 머신러닝 - 데이터 기반 기계가 스스로 학습
* 딥러닝 - "인공 신경망" 기반으로 학습
(위로 갈수록 넓은 개념)

포함 관계
인공지능 > 머신러닝 > 딥러닝

학습을 통해 모델을 만든다.

데이터를 통해 패턴을 배운다.

학습 알고리즘
지도학습, 비지도학습, 강화학습

모델을 데이터로 조정한다. 정확한 모델을 만든다.

빅데이터 - (학습알고리즘) -> 모델 - (새로운 데이터) -> 예측/판단/생성

입력이 들어가면 출력을 하는 함수.

여름에 레모네이드를 판다고 가정.
온도에 따라 팔리는 잔 수 데이터가 있다.

최적화된 함수를 만들어야 함.
각 점과 선과의 오차를 보고 오차가 가장 적은 것을 찾음.
최적화된 함수 찾기. 가장 가까운 함수를 찾는 것

w:weight(가중치)
b:bias(편향)

인공지능의 모델을 만드는 과정.


예측/판단은 어떻게 하냐.
새로운 데이터가 들어오면 새로운 결과를 출력.
인공지능 모델에 없던 것을 넣으면 모델의 의해 결과가 나옴.


인공지능 배울 때 Boston Housing Price 예제를 많이 풀어보게됨.
독립 변수 - 여러 조건들
종속 변수 - 집값

y = w1x1 + w2x3 + ... + w13x13 + b

가장 최적의 함수를 만드는 것

머신러닝과 딥러닝 차이
머신러닝: 모든 학습 알고리즘을 포괄
딥러닝: 인공적인 신경망 기반으로 학습

학습 방법의 차이이고 모델은 같음.

뇌는 뉴런으로 구성되어 있음. 이것과 유사하게 퍼셉트론이라는 개념을 만들어서 여러개의 층을 만들어서 학습. 각각의 파라미터를 두고 조정. 데이터를 넣어 보고 아니면 조금 조정하고.

딥러닝을 적용하니 머신러닝 대비 엄청난 성과

2012년 이후에는 모델들이 딥러닝 기반으로 나오게 됨

그래프 출처: 엄청난 데이터+딥러닝 기술 한국, 의료영상 진단의 성지 될 수 있다 2015년 10월
https://dbr.donga.com/article/view/1101/article_no/7251

=== 2. 최신 AI와 미래

GPT-3 (2020) OpenAI

인풋 대비 아웃풋이 엄청난 결과 창출

텍스트 -> GPT-3 -> 텍스트

소설 쓰기, 이메일 답장, 가계부 완성

https://www.chosun.com/economy/2020/09/06/GXZASOYOYZGH5HRBNWXEG3QPG4/
GPT-3로 할 수 있는 일들/그래픽 김성규 기자

GitHub Copilot
github의 코드를 학습 시킴. 이름을 쓰면 코드를 자동으로 구현해줌.

[source,python]
----
# Get Stock Price
def get_stock_price( # 까지 입력하면 나머지 자동 완성
----

코덱스
https://openai.com/blog/openai-codex/

소설 작가들도 AI활용하기 시작했다
https://www.aitimes.com/news/articleView.html?idxno=145929

GPT-3로 AI 철학자 만들어 보니..."인간 철학자와 구분 힘들어"
https://www.aitimes.com/news/articleView.html?idxno=146149

a photo of a phone from the ...

2022년 4월 DALL-E 2
DALL-E 1에 비해 4배 더 화질이 좋아지고...

다른 화풍이나 스타일로 변경

Inpainting - 부분 수정
Outpainting - 없는 바깥 영역 그리기

Midjourney (2022.07)
이코노미스트 표지

미술대회에 출품했더니 우승

7월 까지 나왔던 것의 문제점은 기업이 모델을 숨겨놓고 입력과 출력만 되도록

2022년 8월 Stable Diffusion 이 나왔는데 허깅페이스라고 모델을 올려놓는 사이트에 모델을 올려둠. 오픈 소스로 배포. 대중화가 일어남.

image to image

Find Tuning
기존 모델을 새로운 데이터로 목적에 맞게 미세조절

Waifu Diffusion 애니메이션에 특화되어 나온 모델

https://blog.novelai.net

3D 디즈니 모델

이케아 가구 모델

구글이 텍스트에서 비디오를 만드는 모델 등장
https://imagen.research.google/video/

페이스북도 있음

텍스트에서 3D 모델을 뽑아주는 모델

텍스트, 이미지를 넣으면 소설, 코딩, 이미지, 영상, 소리, 웹툰, ... 이 나오는 세상

서울웹툰아카데미(SWA)에서 알려드리는 웹툰 작가 되는 방법
https://toonspoon.onstove.com/kr/view/4296897

게임, 음악, 안무, 패션, ... 설계...

생각을 텍스트로

앞으로의 교육에 있어 중요한 부분

큰틀의 설계 (기획의 영역), 디테일 수정

Learn by doing

---

🎬Stable Diffusion 완벽 가이드 영상
https://youtu.be/emObTucGMOA

🎬Dreambooth 파인튜닝 하는 방법
https://youtu.be/vL1t2UcE998

🎬인공지능 만들어보기
https://youtu.be/USQGTW34lO8

웹개발 5주 완성
jocoding.net

목차
00:00 미리보기
00:08 목차 소개
00:39 인공지능의 개념
01:13 인공지능, 머신러닝, 딥러닝 차이
02:05 인공지능 모델을 만드는 방법
02:42 인공지능의 개념 한장 정리
03:36 기계가 학습하는 방법
07:29 딥러닝이란?
08:48 최신 AI와 미래
08:55 최초의 초거대 AI 모델 GPT-3의 등장
10:15 코딩해주는 인공지능의 등장
11:17 한국어 초거대 AI
12:15 text2img
14:14 Stable Diffusion과 AI의 대중화
16:08 지금도 쏟아지는 파인튜닝된 모델
16:14 영상, 오디오, 3D모델 등 생성하는 인공지능 등장
16:57 현재와 미래의 작업 방법
18:10 생각을 텍스트로 바꿔주는 기술
18:42 앞으로 중요한 역량
20:10 Q&A



== History

=== 2021년 6월 AI가 반도체 설계
구글이 일부 공개한 소름돋는 사진, 인공지능이 스스로 진화해버린 역사적인 순간 2021.07.11
https://www.youtube.com/watch?v=_rs4CK5-ss0

2021년 6월 구글과 스탠포드 연구진. AI가 6시간만에 반도체 설계



=== 2016년 3월 이세돌vs알파고 Google DeepMind Challenge Match
구글 딥마인드사의 바둑 인공지능 프로그램인 알파고와 한국의 프로 기사인 이세돌 九단과의 바둑 대국.

기간: 2016년 3월 9일 ~ 3월 15일

5회 대국이 있었고 4회만 이세돌이 이기고 나머지는 알파고가 이겼음


