= 삼성 울트라북 NT530U4B-S54

:hardbreaks:

== 사양
2012년


== 윈도우10 설치
성공한 방법. 윈도우10 설치 USB 준비. 윈도우10 설치 USB를 인식할 수 있는 데스크탑 컴퓨터 준비.
노트북의 SSD를 뽑아냄.
데스크탑에 노트북의 SSD 연결하고 윈도우10 설치 USB로 부팅 해서 노트북의 SSD에 윈도우10 설치를 진행.
파일들을 설치 하고 재부팅 될 때 컴퓨터를 끄고 SSD를 다시 노트북에 연결해서 이후 설치 진행

=== 키보드는 101키로 설정

101키 종류1로 했는데 잘 되는 거 같음

참고
https://answers.microsoft.com/ko-kr/windows/forum/windows_10-ime/%EC%9C%88%EB%8F%84%EC%9A%B010/5bf360b5-deb1-4abe-b019-aa484753ab57

https://blog.naver.com/ksiimn239/221241253468

=== PCI 단순 통신 컨트롤러
3DP Chip 에서 메인보드 드라이버 설치 하면 됨

==== References
http://blog.naver.com/PostView.nhn?blogId=juwaa1004&logNo=220699609557

인텔 홈페이지 들어가서 드라이버 다운 받으면 된다는데 지금은 링크 깨짐.

그냥 3DP Chip에서 메인보드 드라이버 설치 하니 해결 됨

=== 알 수 없는 장치 ACPI SAM0714

에어플레인 모드 컨트롤 장치(AIRPLANE MODE CONTROL)
비행기 모드 관련 드라이버


https://blog.naver.com/medserious12/221342959364[삼성(SAMSUNG) NT270 모델 노트북 "알수 없는 장치" "ACPI\SAM0714\1" 드라이버 설치하기 - 안양컴퓨터수리점 즐겨찾기컴퓨터 2018.08.21]

삼성 서비스 사이트 접속이 안되는 거 같아서

https://blog.naver.com/7773951/220075298605

여기 있는 거 받아서 설치 함

=== 부팅 느려짐. 검은 화면 1~2분. 그래픽 카드 설정 이슈

드라이버 업데이트 해서 해결 했다는 글들이 보이는데 나는 실패 했음

대신 ULPS라는 기능을 비활성화 하는 방법으로 성공했음


==== References
https://blog.naver.com/hanmindbend/221122424264[삼성전자 NT530U4B-S57L 윈도우 10 부팅 느림(느려짐) 해결 방법 2017.10.22]

NT530U4B-S54 2018-04-18 추가 테스트 했다는 문구가 있음

드라이버 업데이트 해서 해결 했다고 함

https://vlee.kr/2770[삼성 노트북 (NT530U4B-S5H) 윈도우10 설치 생명연장 2018.09.28]

regedit -> 찾기 EnableUlps -> 값을 0으로 변경

https://community.amd.com/t5/graphics/ulps-how-to-disable/td-p/228333[ULPS: How to disable 2014.05.08]

== 정리
* https://junho85.pe.kr/1913[삼성전자 시리즈5 노트북 NT530U4B-S54 윈도우10 설치 2차 시도 2021.05.08]
* https://junho85.pe.kr/1911[삼성전자 시리즈5 노트북 NT530U4B-S54 윈도우10 설치 가능? 2021.05.06]
