= 2. 주 이야기 - 공허의 유산

== 아이어

=== 1. 아이어를 위하여! (아이어)

유인해서 처리 하면서 진행. 그냥 달려 가다가 몰살 당할 수도 있음.

=== 2. 커지는 그림자 - 공허의 구도자에 도달 (아이어)

아르타니스에게 갈 때는 그냥 제라툴 혼자 열심히 가면 됨

=== 3. 아둔의 창 - 아둔의 창 활성화 (아이어)

왼쪽 입구에 3개 박아 두면 적군이 쉽게 쳐들어 올 수 없음



== 코랄

=== 4.하늘 방패 (코랄)

평형 유지 장치 확보 및 태양석 확보


=== 5.전우 (코랄)

불멸자위주로 뽑고 추적자

불멸자가 어느정도 모이면 유물 발동시 뫼비우스 군사들도 멈출 때 공격을 나선다

=== 6. 아몬의 손아귀 (샤쿠라스)

첫번째 공허분쇄자는 초반 암흑기사 4명 미리 보내서 처리

포자촉수는 암흑기사로 처리 하고 감시군주는 아둔의창으로 처리

=== 7. 최후의 항전 - 사원 과부하 (샤쿠라스)

보너스 목표가 저그 15억인데 쉽지 않음.

기지 방어를 열심히 해야 됨.

후반으로 가면 광물이 남아날 수 있음. 광자포라도 열심히 깔아둔다.

초반에는 암흑기사로 주로 방어한다. 중반부터는 감시군주가 같이 날아 오는데 궤도 폭격으로 처리해 준다.

천정석 파괴하러 갈 때 감시군주가 있는데 궤도 폭격으로 미리 처리해 두는 것이 좋다.

천정석 부술 때 암흑기사 5기 정도 보내주면 된다.


글라시우스로 여행간다.


=== 8. 금단의 무기 (글라시우스)

궤도 폭격 보다 태양의 창이 유리함


기술 보관소 찾으러 옴

알라라크 등장

추적자와 광전사 위주로 구성. 파수기는 중간중간 나오니 많이 뽑을 필요는 없음.

2시 방향 프로토스 기지는 중요한 거 없고 방어가 강하니 굳이 부수지 않아도 됨

다만 기지로 공격이 종종 들어 오는데 남는 광물로 광자포를 적당히 깔아 주어 방어한다.

언덕위로 분광기 올라올 때 빠르게 처리해 주는 것이 좋음. 분광기가 설치 되면 광자포 등이 생겨나서 시간을 끌게 됨.

마지막 무기고 부근에서는 분광기에서 광전사가 계속 나오는데 무시하고 입구 열고 들어가면 됨


울나르로 이동

== 9. 통합의 사원 - 사원 진입 (울나르)

불사조 위주로 뽑고 천상석을 차지하면 광자포를 깔아 준다

지상 유닛은 태양의 창으로 공격한다

적이 천상석을 뺏으러 오면 광자포와 태양의 창의로 방어한다

== 10. 무한의 순환 - 젤나가 찾기 (울나르)

차원 분광기가 나오면 차원 분광기를 먼저 처치 하는 것이 좋음

수호자가 아몬 병력과 싸우고 있으면 다 싸우고 남은 녀석을 처치 하면 편리하다

맹독충 만들어서 함께 달려 간다.

아르타니스의 회생 기능을 적극 활용한다.



알라라크 등장

전쟁의회에서 탈다림 군사로 지정 가능

피닉스 배치를 사용 할 수 있으나 태양석이 100필요하니 태양의 창 등을 빼고 피닉스 배치에 사용?


== 11. 망각의 전령 - 아르타니스 구출 (울나르)

젤나가의 함은 기지 왼쪽, 중앙 왼쪽 위, 12시

쉽지 않음.

아둔의 창 조합: 태양의 창, 보호막 과충전

가스가 부족하면 저그 가스도 먹음

암흑기사를 주 병력으로 한다.

공중유닛은 태양의 창, 불사조, 추적자 등을 활용한다.

캐리건, 울트라리스크 등이 지원 오면 보호막 과충전을 활용한다.


여행: 엔디온 (정화자 미션), 슬레인 (알라라크 미션)

엔디온으로 이동

== 12. 과거의 봉인을 풀고 - 정지장 잠금 장치 해제 (엔디온)

거신을 주로 활용

공중유닛은 추적자, 태양의 창 등을 이용한다.

동굴이 나오면 태양의 창으로 빠르게 막아 준다.

== 13. 정화 - 사이브로스 재가동 (사이브로스)

꽤 어려움.

초반 방어

왼쪽 무력화 회로 3개 처리. 마지막 한개는 태양의 창으로 하면 편리. 이후에는 동맹(정화자)들이 쓸어 줌. 7시 쓸 때 일꾼 하나 보내서 확장 짓자


여행. 레반스카, 슬레인

슬레인으로 이동해서 탈다림 미션을 진행하자


== 14. 의례의 계단 - 수효병 제거 (슬레인)

공허 포격기 열심히 뽑아서 공격과 방어 하면 됨

== 15. 라크쉬르 - 말라쉬 축출 (슬레인)

풀업 공허 포격기로 밀어 붙이면 이길 수 있음

중앙에 빠른 확장을 해서 가스를 빨리 캘 수 있도록 한다

광물이 남는 편이라 광자포로 깔면서 가도 됨. 매트릭스 과부하가 있으면 수정탑 동력장 내에서 아군 유닛 속도가 증가하니 유용함.

위쪽 기지에도 광자포 방어 깔아 두는데 종종 공중 장거리 공격 오면 태양의 창 3방 장거리 유닛에 먹여서 처리 한다.


== 16.기사단의 자격 - 혼종 교배 시설 파괴 (레반스카)

자원 캐고 우주모함 모으면서 조금씩 이동함

비행 유닛 공격해 오면 태양의 창으로 방어함




== 17. 기사단의 귀환 -  (아이어)

보라준과 알라라크

피닉스, 카락스

아르타니스




== 18. 숙주 - 아몬의 숙주 육신 파괴 (아이어)

초반 방어 하면서 우주모함 모아서 쓸어도 됨

== 19. 구원 - 중추석 방어 (아이어)

불사조와 광자포
