= 2. 주 이야기 - 공허의 유산

== 아이어

=== 1. 아이어를 위하여! (아이어)

유인해서 처리 하면서 진행. 그냥 달려 가다가 몰살 당할 수도 있음.

=== 2. 커지는 그림자 - 공허의 구도자에 도달 (아이어)

아르타니스에게 갈 때는 그냥 제라툴 혼자 열심히 가면 됨

=== 3. 아둔의 창 - 아둔의 창 활성화 (아이어)

왼쪽 입구에 3개 박아 두면 적군이 쉽게 쳐들어 올 수 없음



== 코랄

=== 4.하늘 방패 (코랄)

평형 유지 장치 확보 및 태양석 확보


=== 5.전우 (코랄)

불멸자위주로 뽑고 추적자

불멸자가 어느정도 모이면 유물 발동시 뫼비우스 군사들도 멈출 때 공격을 나선다

=== 6. 아몬의 손아귀 (샤쿠라스)

첫번째 공허분쇄자는 초반 암흑기사 4명 미리 보내서 처리

포자촉수는 암흑기사로 처리 하고 감시군주는 아둔의창으로 처리

=== 7. 최후의 항전 - 사원 과부하 (샤쿠라스)

보너스 목표가 저그 15억인데 쉽지 않음.

기지 방어를 열심히 해야 됨.

후반으로 가면 광물이 남아날 수 있음. 광자포라도 열심히 깔아둔다.

초반에는 암흑기사로 주로 방어한다. 중반부터는 감시군주가 같이 날아 오는데 궤도 폭격으로 처리해 준다.

천정석 파괴하러 갈 때 감시군주가 있는데 궤도 폭격으로 미리 처리해 두는 것이 좋다.

천정석 부술 때 암흑기사 5기 정도 보내주면 된다.


글라시우스로 여행간다.


=== 8. 금단의 무기 (글라시우스)

궤도 폭격 보다 태양의 창이 유리함


기술 보관소 찾으러 옴

알라라크 등장

추적자와 광전사 위주로 구성. 파수기는 중간중간 나오니 많이 뽑을 필요는 없음.

2시 방향 프로토스 기지는 중요한 거 없고 방어가 강하니 굳이 부수지 않아도 됨

다만 기지로 공격이 종종 들어 오는데 남는 광물로 광자포를 적당히 깔아 주어 방어한다.

언덕위로 분광기 올라올 때 빠르게 처리해 주는 것이 좋음. 분광기가 설치 되면 광자포 등이 생겨나서 시간을 끌게 됨.

마지막 무기고 부근에서는 분광기에서 광전사가 계속 나오는데 무시하고 입구 열고 들어가면 됨


울나르로 이동

== 9. 통합의 사원 - 사원 진입 (울나르)



== 10. 무한의 순환 (울나르)

== 11. 망각의 전령 (울나르)


=== 6.기사단의 자격 (레반스카)






== 정화자


=== 13. 과거의 봉인을 풀고 (엔디온)

=== 14. 정화 (사이브로스)

== 탈다림

=== 15. 의례의 계단 (슬레인)

=== 16. 라크쉬르 (슬레인)

== 아이어로 귀환

=== 17. 기사단의 귀환 (아이어)

=== 18. 숙주 (아이어)

=== 19. 구원 (아이어)

