:hardbreaks:
= JPA Delete

== Spring

알아두면 좋은 것들

@Modifying
flushAutomatically 기본값 false
clearAutomatically 기본값 false



== References


https://velog.io/@_koiil/JPA-Delete-%EC%A0%95%EC%B1%85[JPA Delete 정책 (soft delete + bulk delete)

hard delete (물리 삭제) delete 명령어를 사용하여 직접 데이터를 삭제하는 방법
soft delete (논리 삭제) update 명령어를 사용하여 삭제 여부를 알수 있는 컬럼에 데이터가 삭제되었다는 값을 넣어서 표현하는 방법

JPARepository를 이용한 delete의 문제점
1:N의 Join 관계에서 1의 id를 가지고 N의 레코드를 삭제하면, JPA는 N번의 delete 쿼리를 날리게 됨

bulk delete 하는 방법
(deprecated) deleteInBatch (deleteAllInBatch로 대체되었음)

deleteAllInBatch
deleteAllByIdInBatch

기존 delete 처럼 find -> get id -> delete X n 이 아니라 delete where id=? or id=? or id=?... 이기 때문에 한번의 쿼리로 대량의 삭제가 가능
하지만 entity 혹은 id list를 인자로 받아야 하기 때문에 결국 최소 한번은 엔티티에 접근해야 함

@Query와 @Modifying

@Query 로 커스텀 쿼리를 생성하는 방법
@Modifying 은 영속성 컨텍스트에 캐싱된 데이터와 관련된 어느테이션

JPA에서 조회를 실행할 시에 영속성 컨텍스트에 있는 1차 캐시를 확인해서 해당 엔티티가 1차 캐시에 존재한다면 DB에 접근하지 ㅇ낳고, 1차 캐시에 있는 엔티티를 반환함

하지만 벌크 연산은 1차 캐시를 포함한 영속성 컨텍스트를 무시하고 바로 Query를 실행하기 때문에 영속성 컨텍스트는 데이터 변경을 알 수 없음

때문에 벌크 연산 실행 시, 1차 캐시 (영속성 컨텍스트)와 DB의 데이터 싱크가 맞지 않게 되기 때문에 @Modifying 어노테이션을 추가해줘야 함

또한 @Modifying 을 사용할 때는 clearAutomatically=true, flushAutomatically=true 속성을 주어, 연산 직 후 자동으로 영속성 컨텍스트를 clear하고 DB에 flush 할 것인지를 명시해 주는 것이 좋음

JPA에서 대량의 데이터를 삭제할때 주의해야할 점 2017.10.16
https://jojoldu.tistory.com/235

