:hardbreaks:
= function* - generator function

[source,javascript]
----
function* generator(i) {
  yield i;
  yield i + 10;
}

const gen = generator(10);

console.log(gen.next().value); // 10
console.log(gen.next().value); // 20
----

====
Generator 함수는 호출되어도 즉시 실행되지 않고, 대신 함수를 위한 Iterator 객체가 반환됩니다. Iterator의 next() 메서드를 호출하면 Generator 함수가 실행되어 yield 문을 만날 때까지 진행하고, 해당 표현식이 명시하는 Iterator로부터의 반환값을 반환합니다. yield* 표현식을 마주칠 경우, 다른 Generator함수가 위임(delegate)되어 진행됩니다.

이후 next() 메서드가 호출되면 진행이 멈췄던 위치에서부터 재실행합니다. next()가 반환하는 객체는 yield문이 반환할 값(yielded value)을 나타내는 value 속성과, Generator 함수 안의 모든 yield 문의 실행 여부를 표시하는 boolean 타입의 done 속성을 갖습니다. next() 를 인자값과 함꼐 호출할 경우, 진행을 멈췄던 위치의 yield 문을 next() 메서드에서 받은 인자값으로 치환하고 그 위치에서 다시 실행하게 됩니다.
====

[source,javascript]
----
function* generator(i) {
  yield i;
  yield i + 10;
}

const gen = generator(10);

gen.next()
> {value: 10, done: false}
gen.next()
> {value: 20, done: false}
gen.next()
> {value: undefined, done: true}
----

== References
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/function*

https://www.ecma-international.org/ecma-262/6.0/#


https://leego.tistory.com/entry/Generator%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C[[JavaScript\] Generator란 무엇일까? 2021.09.04]

[source,js]
----
function* generateSequence() {
    yield 1;
    yield 2;
    return 3;
}
----

* 일반 함수는 function 키워드로 시작한다면, 제너레이터 함수는 function* 키워드로 시작한다. (화살표 함수는 사용할 수 없다.)
* 제너레이터 함수 안에는 yield 구문이 존재한다. yield 구문의 문법은 return 구문과 비슷하다. 차이점은 return 은 한번만 실행되지만, 제너레이터 함수의 yield 는 여러번 실행된다는 것이다. yield 구문은 제너레이터의 실행을 멈췄다가 다음에 다시 시작할 수 있게 만든다.

제너레이터 함수는 일반 함수와 동작 방식이 다른데, 제너레이터 함수를 호출하면 코드가 실행되지 않고, 제너레이터 객체가 반환된다.

[source,js]
----
let generator = generateSequence();
----

console.dir(generator) 를 찍어보면 제너레이터 객체를 반환하는 것을 알 수 있다.

이 제너레이터 객체는 이터러블(iterable)이면서 동시에 이터레이터(iterator)인 객체이다. 따라서 next 메서드를 호출하기 위해 Symbol.iterator 메서드로 이터페이터를 별도 생성할 필요가 없다.

[source,js]
----
console.log(generator.next());
// {value: 1, done: false}

console.log(generator.next());
// {value: 2, done: false}

console.log(generator.next());
// {value: 3, done: true}
----
제너레이터 객체의 .next() 메서드를 호출할 때마다, 제너레이터 객체는 스스로 깨어나서 다음번 yield 문에 다다를 때까지 실행된다.

[source,js]
----
for (let value of generator) {
    console.log(value); // 1, 2
}
----

참고로 generator 를 for-of문으로 돌리면 1,2 까지만 출력된다. 이유는 for-of 이터레이션이 done: true 일 때 마지막 value 를 무시하기 때문이다. 그러므로 for-of를 사용했을 때 모든 값이 출력되길 원한다면 yield로 값을 반환해야한다.

