:hardbreaks:
= 전사 구성원들이 사용하는 배치 데이터 플랫폼 만들기 - Airflow Advanced

Airflow 운영 고도화를 위한 고군분투기

https://tech.socarcorp.kr/data/2022/11/09/advanced-airflow-for-databiz.html

Airflow는 Airbnb에서 개발한 워크플로우 관리 오픈소스. 많은 기업에서 데이터 파이프라인을 자동화할 때 사용하는 툴

쏘카에서는 데이터 분석가, 데이터 사이언티스트, AI 엔지니어 등 다양한 사용자들이 Airflow DAG을 통하여 파이프라인을 직접 구출할 수 있음. 대신 다양한 사요자가 Airflow를 불편함 없이 이용하기 위해 관리자가 Airflow의 사용범주와 개발 방식을 잘 정의하는 것이 중요함.

쏘카에서는 데이터 통합 저장소(데이터 레이크, 웨어하우스)로 BigQuery를 사용하고 있음. 기본적으로 외부 데이터 소스(Open API, RDBMS, S3 등)와 BigQuery 원본 데이터 셋을 BigQuery로 가공/적재하는 작업에 Airflow를 사용할 것을 권장하고 있음. 또한 DAG는 Data Lake, Data Mart, Monitoring, Crawling 등 각 용도에 맞게 분류하여 관리되고 있음. (단순 스케줄링을 필요로 하는 작업은 Airflow의 사용을 지양하고 K8s Cronjob이나 Github Action 등을 활용하는 것을 권장하고 있음)

Airflow Github Repository의 Branch 이름이 특정 조건을 만족하면 CI/DI 파이프라인을 거쳐서 개발 클러스터에 Branch 별로 Airflow 서비스가 독립적으로 생성됨

과거 Airflow 사용자는 DAG을 생성/변경하기 위해서 기본적으로 feature Branch를 생성하여 변경 커밋을 원격 Branch에 푸시 하였음. 그러면 Git Sync를 통해 Airflow에 DAG이 동기화되어 테스트가 가능했음.

== 문제점
사용자가 독립된 Airflow 개발 환경을 쓸 수 있는 것은 큰 장점. 운영과 분리된 환경에서 테스트 가능. Github를 SoT(Source of Truth)로 삼아 코드 퀄리티 관리가 용이. 하지만 기존 방식의 Airflow 문제점이 있었음.

1. 개발 환경의 Airflow의 에러 발생 및 관리자/컴퓨팅 리소스 낭비
2. 많은 사용자들이 사용하기엔 불친절한 개발 환경, 긴 피드백 루프
3. Airflow 1 버전의 고질적인 문제들
4. 코드 보안에 취약, 사용자 개인에 대한 권한 체계 부족
5. 쳬게적이지 않은 오류 대응 프로세스 및 모니터링 환경

문제점 1 - 개발 환경의 Airflow의 에러 발생 및 관리자/컴퓨팅 리소스 낭비

개발 환경의 Airflow는 Github Branch를 기반으로 생애 주기가 결정됨. 따라서 사용자가 작업을 완료하고 Branch를 삭제하면 개발 환경의 Airflow는 함께 내려가게 됨. 그러나 사용자는 Branch를 만들고 작업하다가 중간에 다른 작업을 하는 경우들이 많았고, 이에 Airflow는 계속 유휴 상태로 남아있어 K8s Node의 자원을 차지하였음.

더불어 당시 Airflow를 K8s에 배포하기 위해 사용한 Helm Chart(Community 버전)도 간헐적으로 원인 모를 에러가 발생하였음. 이에 따라 관리자는 Airflow 에러를 수정하고 사용자와 커뮤니케이션하는 과정에서 피로도가 높았음.

문제점2 - 많은 사용자들이 사용하기엔 불친절한 개발 환경, 긴 피드백 루프

개발 환경의 Airflow는 Git Sync를 통해 Github Repository의 코드를 동기화함. 사용자가 DAG의 변경 사항을 개발 클러스터에 반영하기 위해 매번 Commit을 해야 하는 것도 불편했으며 운영하는 DAG의 개수들이 많다 보니 Push 때마다 동기화 시간이 1분 이상 걸리디고 했음. 이런 상황에서 사용자가 코드를 작성하면서 계속해서 동작 확인을 하기 위해선 Commit당 매번 1분 이상 기다려야 했음. 이는 피드백 루프와 개발 시간이 길어진다는 것을 의미함.

또한 개인 노트북 환경에서 코드를 작성하기 위해선 Airflow 관련 구성 의존성들을 설치해야 하고 기본 개발 환경을 설정해야 함. 하지만 이에관한 가이드 문서들이 부족하였으며 일부 Mac OS 버전에서는 의존성이 제대로 설치되지 않는 문제들도 있었음.

문제점3 - Airflow 1 버전의 고질적인 문제들

기존 1버전 대 Airflow는 DAG 개수가 늘어나면 DAG Parsing 시간이 오래 걸리는 치명적인 문제가 있었음. 그때 당시 쏘카에서 운영하는 DAG은 수백 개였고 점점 DAG이 늘어날 때마다 Task Instance들의 스케줄링이 점점 밀리게 되었음. 그리고 DAG Parsing 프로세스가 백그라운드에서 동작하고 있다 보니 웹에 접근했을 때 속도가 느렸음. 그때 당시 K8s Node의 자원을 스케일 업해봤지만 크게 개선되는 부분은 없었고 단순 스케일 업보다는 조금 더 근본적인 해결책이 필요했음.


TODO
