:hardbreaks:
= 전사 구성원들이 사용하는 배치 데이터 플랫폼 만들기 - Airflow Advanced

Airflow 운영 고도화를 위한 고군분투기

https://tech.socarcorp.kr/data/2022/11/09/advanced-airflow-for-databiz.html

Airflow는 Airbnb에서 개발한 워크플로우 관리 오픈소스. 많은 기업에서 데이터 파이프라인을 자동화할 때 사용하는 툴

쏘카에서는 데이터 분석가, 데이터 사이언티스트, AI 엔지니어 등 다양한 사용자들이 Airflow DAG을 통하여 파이프라인을 직접 구출할 수 있음. 대신 다양한 사요자가 Airflow를 불편함 없이 이용하기 위해 관리자가 Airflow의 사용범주와 개발 방식을 잘 정의하는 것이 중요함.

쏘카에서는 데이터 통합 저장소(데이터 레이크, 웨어하우스)로 BigQuery를 사용하고 있음. 기본적으로 외부 데이터 소스(Open API, RDBMS, S3 등)와 BigQuery 원본 데이터 셋을 BigQuery로 가공/적재하는 작업에 Airflow를 사용할 것을 권장하고 있음. 또한 DAG는 Data Lake, Data Mart, Monitoring, Crawling 등 각 용도에 맞게 분류하여 관리되고 있음. (단순 스케줄링을 필요로 하는 작업은 Airflow의 사용을 지양하고 K8s Cronjob이나 Github Action 등을 활용하는 것을 권장하고 있음)

Airflow Github Repository의 Branch 이름이 특정 조건을 만족하면 CI/DI 파이프라인을 거쳐서 개발 클러스터에 Branch 별로 Airflow 서비스가 독립적으로 생성됨

과거 Airflow 사용자는 DAG을 생성/변경하기 위해서 기본적으로 feature Branch를 생성하여 변경 커밋을 원격 Branch에 푸시 하였음. 그러면 Git Sync를 통해 Airflow에 DAG이 동기화되어 테스트가 가능했음.

== 문제점
사용자가 독립된 Airflow 개발 환경을 쓸 수 있는 것은 큰 장점. 운영과 분리된 환경에서 테스트 가능. Github를 SoT(Source of Truth)로 삼아 코드 퀄리티 관리가 용이. 하지만 기존 방식의 Airflow 문제점이 있었음.

1. 개발 환경의 Airflow의 에러 발생 및 관리자/컴퓨팅 리소스 낭비
2. 많은 사용자들이 사용하기엔 불친절한 개발 환경, 긴 피드백 루프
3. Airflow 1 버전의 고질적인 문제들
4. 코드 보안에 취약, 사용자 개인에 대한 권한 체계 부족
5. 쳬게적이지 않은 오류 대응 프로세스 및 모니터링 환경

문제점 1 - 개발 환경의 Airflow의 에러 발생 및 관리자/컴퓨팅 리소스 낭비

개발 환경의 Airflow는 Github Branch를 기반으로 생애 주기가 결정됨. 따라서 사용자가 작업을 완료하고 Branch를 삭제하면 개발 환경의 Airflow는 함께 내려가게 됨. 그러나 사용자는 Branch를 만들고 작업하다가 중간에 다른 작업을 하는 경우들이 많았고, 이에 Airflow는 계속 유휴 상태로 남아있어 K8s Node의 자원을 차지하였음.

더불어 당시 Airflow를 K8s에 배포하기 위해 사용한 Helm Chart(Community 버전)도 간헐적으로 원인 모를 에러가 발생하였음. 이에 따라 관리자는 Airflow 에러를 수정하고 사용자와 커뮤니케이션하는 과정에서 피로도가 높았음.

문제점2 - 많은 사용자들이 사용하기엔 불친절한 개발 환경, 긴 피드백 루프

개발 환경의 Airflow는 Git Sync를 통해 Github Repository의 코드를 동기화함. 사용자가 DAG의 변경 사항을 개발 클러스터에 반영하기 위해 매번 Commit을 해야 하는 것도 불편했으며 운영하는 DAG의 개수들이 많다 보니 Push 때마다 동기화 시간이 1분 이상 걸리디고 했음. 이런 상황에서 사용자가 코드를 작성하면서 계속해서 동작 확인을 하기 위해선 Commit당 매번 1분 이상 기다려야 했음. 이는 피드백 루프와 개발 시간이 길어진다는 것을 의미함.

또한 개인 노트북 환경에서 코드를 작성하기 위해선 Airflow 관련 구성 의존성들을 설치해야 하고 기본 개발 환경을 설정해야 함. 하지만 이에관한 가이드 문서들이 부족하였으며 일부 Mac OS 버전에서는 의존성이 제대로 설치되지 않는 문제들도 있었음.

문제점3 - Airflow 1 버전의 고질적인 문제들

기존 1버전 대 Airflow는 DAG 개수가 늘어나면 DAG Parsing 시간이 오래 걸리는 치명적인 문제가 있었음. 그때 당시 쏘카에서 운영하는 DAG은 수백 개였고 점점 DAG이 늘어날 때마다 Task Instance들의 스케줄링이 점점 밀리게 되었음. 그리고 DAG Parsing 프로세스가 백그라운드에서 동작하고 있다 보니 웹에 접근했을 때 속도가 느렸음. 그때 당시 K8s Node의 자원을 스케일 업해봤지만 크게 개선되는 부분은 없었고 단순 스케일 업보다는 조금 더 근본적인 해결책이 필요했음.


문제점4 - 코드 보안에 취약, 사용자 개인에 대한 권한 체계 부족

다수의 사용자들이 Airflow를 사용하면서 Api Key나 Secret 정보들을 그대로 하드코딩하는 경우들이 있었음. 특히 Airflow 사용 목적 상 외부 데이터 소스/저장소와 통신해야 하는 경우들이 많아 위 문제들이 빈번하게 발생했음.

또한 팀 별로 공용 계정을 사용했기 때문에 간혹 Connection, Variable이 지워지거나 실행되던 Task가 갑자기 종료되는 문제들이 발생했었으며, 정확한 히스토리 추적이 힘들어지는 문제가 있었음.

문제점5 - 체계적이지 않은 오류 대응 프로세스 및 모니터링 환경

기존에는 Airflow DAG가 실패했을 때 알림을 보내는 슬랙 채널이 존재했음. 보통 메시지가 오면 관리자 혹은 히스토리를 잘 알고 있는 사용자가 해당 DAG의 책임자에게 라우팅을 해주는 방식이었음. 하지만 담당자를 제대로 파악하고 대응하기까지 시간이 걸리는 경우들이 있었고, 담당잘르 제때 파악하지 못하는 경우들도 있었음.

또한 Airflow가 동작하는 K8s 환경에 대한 체계적인 모니터링 환경을 구축하고 있지 못했음.

=== 1.3. 해결 방안 모색

Airflwo를 운영하면서 드러난 문제들을 개선하기 위해 아래와 같은 해결방안들을 세웠음. 구체적인 내용들은 밑에서 더 상세하게 풀어내도록 함.

문제점과 해결 방안

개발 환경의 Airflow의 에러 발생 및 리소스 낭비. 불친절한 개발 환경, 긴 피드백 루프
-> 개발 환경 개선 및 개발 주기 단축하기

Airflow 1 버전의 고질적인 문제들
-> Airflow 2 버전 마이그레이션 및 스케일 업

코드 보안에 취약하고, 사용자 개인에 대한 권한 체계 부족
-> 보안 강화 및 RBAC 적용

체계적이지 않은 오류 대응 프로세스 및 모니터링 환경
-> 체계적인 모니터링 환경 구축

== 2. 개발 환경 개선 및 개발 주기 단축하기

=== 2.1. 목적
기존 Airflow 개발 환경은 Airflow의 생애 주기가 Branch에 의존적이기 때문에 Branch가 남아있다면 자원을 유휴상태로 낭비하는 경우들이 많았음. 또한 Branch가 삭제되었을 때 CI/CD 파이프라인의 이슈로 Airflow가 제대로 삭제되지 않는 문제들이 있었음. 그리고 K8s + Git Sync 조합은 DAG이 많을수록 동기화 속도가 느려져서 피드백 루프와 개발 속도의 저하를 유발했음

그래서 개발 환경을 노트북(로컬 환경)에서 쉽게 구축할 수 있다면 생산성이 더 높아질 것이라고 판단하였음. 기본적으로 Docker는 OS에 크게 상관없이 표준을 따르기 때문에 로컬 환경에 Docker Compose를 띄워서 개발 환경을 개선하는 작업을 진행했음

결과적으로 로컬 환경을 도입하여서 아래와 같이 개발 생산성으 ㄹ높이고 인적/클라우드 비용의 절감을 이끌어냈음.

* Airflow 서버를 띄우는 시간 단축: 5분 -> 1분
* 개발 피드백 루프 시간 단축 : 1분(Commit -> Sync) -> 5초
* 개발 클러스터에서 유휴 Airflow들이 Node를 점유하였던 문제 해결 : 2개 이상의 VM 절약
* Docker라는 표준 환경을 통해 Airflow 서버의 불안정성을 낮추고 관리 비용을 줄임



TODO
