:hardbreaks:
= Kotlin reified

realized at runtime. 런타임 시 실체화되는 제네릭 타입을 나타냄

발음: 리어파이드


== References

https://velog.io/@miot2j/Kotlin-Inline-Funtions-%EA%B3%BC-Reified-%EC%82%AC%EC%9A%A9-%EC%9D%B4%EC%9C%A0[Inline-Funtions 과 Reified 사용 이유 2021.12.12]

인라인(inline) 키워드는 자바에서는 제공하지 않는 코틀린만의 키워드
코틀린 공식문서의 인라인 평선 (https://kotlinlang.org/docs/inline-functions.html[inline 공식문서])을 보면 코틀린에서 고차함수(High order functions, 함수를 인자로 전달하거나 함수를 리턴)를 사용하면 패널티가 발생한다고 나와있음

패널티란 추가적인 메모리 할당 및 함수호출로 Runtime overhead가 발생한다는 것으로, 람다를 사용하면 각 함수는 객체로 변환되어 메모리 할당과 가상 호출 단계를 거치는데 여기서 런타임 오버헤드가 발생

inline functions는 내부적으로 함수 내용을 호출되는 위치에 복사하며, Runtime overhead를 줄여준다.

고차함수(함수를 인자로 전달하거나 함수를 리턴하는 함수)를 컴파일 하면 자바 파일이 생성됨

[source,kotlin]
----
fun doSomethingElse(lambda: () -> Unit) {
  println("Doing something else")
  lambda()
}
----

컴파일된 자바 코드

[source,java]
----
public static final void doSomethingElse(Function0 lambda) {
  System.out.println("Doing something else");
  lambda.invoke();
}
----

Functional Interface인 Function 객체를 파라미터로 받고 invoke 메서드를 실행함.

여기서 invoke란 코틀린 표준 라이브러리 메소드 시그니처에 따라(변수의 개수에 따라 22까지 정의됨) 인터페이스가 생성되어 있고, 내부에 invoke() 메서드에 람다식을 구현하고 해당 객체를 파라미터로 사용한다.

[source,kotlin]
----
fun doSomething() {
  println("Before lambda")

  doSomethingElse {
    println("Hello, world!")
  }
  println("After lambda")
}
----

컴파일된 자바 코드

[source,java]
----
public static final void doSomething() {
  System.out.println("Before lambda");
  doSomethingElse(new Function() {
    public final void invoke() {
         System.out.println("Inside lambda");
    }
  });
  System.out.println("After lambda");
}
----
컴파일된 코드를 보면 문제점이 있음. 파라미터로 매번 새로운 (new Function()) 객체를 만들어 넣어준다는 것. 이렇게 의미없이 객체로 변환되는 코드가 바로 객체로 변환되는 오버헤드이자 패널티

Inline-Functions 로 오버헤드 해결하기


[source,kotlin]
----
inline fun doSomethingElse(lambda: () -> Unit) {
  println("Doing something else")
  lambda()
}
----

컴파일된 자바 코드

[source,java]
----
public static final void doSomething() {
  System.out.println("Before lambda");
  System.out.println("Doing something else");
  System.out.println("Inside lambda");
  System.out.println("After lambda");
}
----
새로운 객체를 생성하는 부분이 사라지고

[source,java]
----
  System.out.println("Doing something else");
  System.out.println("Inside lambda");
----

두 코드를 변경된 것을 알 수 있다.

추가로 람다식에 로컬변수를 넣을때 inline 을 사용하면 조금더 성능을 끌어 올릴 수 있는데,

새로운 객체를 생성할때 로컬 변수까지 추가되어 메모리 사용량이 늘어나는데 이 부분을 inline 을 이용해 없앨 수 있기 때문

Reified란?

inline과 함께 refied 키워드를 사용하면 Generics를 사용하는 메소드 까지 처리할 수 있음
범용성 좋은 메소드를 만들기 위해 generics <T> 를 사용할 때가 있음

[source,kotlin]
----
fun <T> doSomething(someValue: T)
----
하지만 이러한 class Type T 객체는 타입에 대한 정보가 런타임에서 Type Erase되어버려 알 수 없어짐. 그래서 실행하면 에러가 발생함
왜냐하면 타입을 알 수 없기 때문.
따라서 Class를 함께 넘겨 type을 확인하고 casting 하는 과정을 거치곤 함.

[source,kotlin]
----
// runtime에서도 타입을 알 수 있게 Class<T> 넘김
fun <T> doSomething(someValue: T, Class<T> type) {
  // T의 타입을 파라미터를 통해 알기에 OK
  println("Doing something with value: @someValue")
  // T::class 가 어떤 class인지 몰라서 Error
  println("Doing something with type: ${T::class.simpleName}")
}
----

*인라인(inline) 함수와 reified 키워드를 함께 사용하면 T type에 대해서 런타임에 접근할 수 있게 해줌*. 따라서 타입을 유지하기 위해서 Class와 같은 추가 파라미터를 넘길 필요가 없어짐

하지만 inline은 만능이 아님
* 기본적으로 JVM의 JIT 컴파일러에 의해서 일반 함수들은 inline 함수를 사용했을 때 더 좋다고 생각되어지면 JVM이 자동으로 만들어주고 있음
* 또한 private 접근자일 경우 사용이 불가능
* 위에서 변한된 자바 바이트 코드를 보면 길이가 더 길어져 너무 긴 메소드에 사용시 메모리가 낭비 될 수 있음
* inline keyword는 1~3줄 정도 길이의 함수에 사용하는 것이 효과적일 수 있음
* 필요시 특정 메소드를 인라인 방식에서 제외 하고 싶다면 noinline 을 사용한다.

https://codechacha.com/ko/kotlin-reified-keyword/[Kotlin - Reifie를 사용하는 이유?]

Reified 키워드는 Generic로 inline function에서 사용되며, Runtime에 타입 정보를 알고 싶을 떄 사용함

Generics는 아래와 같이 T와 같은 문자로 타입을 표현함. 여기서 T는 어떤 타입이든 될 수 있음

[source,kotlin]
----
fun <T> function(argument: T)
----

Generics 코드를 컴파일 할 때 컴파일러는 T가 어떤 타입인지 알고 있음. 하지만 Compile하면서 타입 정보를 제거하여 Runtime에는 T가 어떤 타입인지 모름. 그냥 T로 정해진 객체가 존재할 뿐.

Reified 키워드를 사용하면 Generics function에서 Runtime에 타입 정보를 알 수 있음. 하지만 inline function과 함께 사용할 때만 가능함

> inline function 은 함수 내의 코드를 inline으로 호출하는 위치에 붙여넣어주는 기능. 함수를 호출하지 않기 때문에 성능이 좋음

하지만 긴 코드에 적용을 한다면 코드 양잉 많아지는 성능 문제가 발생할 수 있음. 더 자세한 것은 https://codechacha.com/ko/kotlin-inline-functions/[Kotlin - inline functions 이해하기] 참고

