= 우아한형제들 면접


== References

=== [우.묻.다] 우아한형제들 개발자에게 묻는다. 인터뷰편 1탄 2020.10.29
https://www.youtube.com/watch?v=g5sxpi0sJc4[[우.묻.다\] 우아한형제들 개발자에게 묻는다. 인터뷰편 1탄 2020.10.29]

김지헌. honeymon
이동욱. jojoldu

추천책

스프링 책

Real MySQL, 그림으로 배우는 Http & Network, 대규모 트래픽을 지탱하는

Java in Action
Spring in Action
토비의 스프링 3.1

Boot Spring Boot 출간

스프링 부트와 AWS로 혼자 구현하는...

Q2. 신기술 조사 방법

트위터 추천. 해외 개발자들이 트위터 많이 함. 그 사람들이 올린거 수집.

긱뉴스. xguru 권종혁님이 만든 서비스. RSS Feed 등록하거나 메일링

Q3. 공부하기 귀찮아지면

번아웃 해소 방법 이야기

Q4. 신입으로 돌아가면?

영어공부

Q5. 소프트웨어 스킬 어필

경청을 잘 해야됨. 질문의 의도를 정확하게 파악.

비개발 직군에게 설명하는 연습

Q6. 대학생. 맞지 않는 것 같다는 생각. 개발자분들도? 개발자가 되고자 했던 특별한 게기?

10년. 매일 그 생각. 새로운 적성 찾아봄.

웹툰. SNS. 싫어하지 않은거에서 경제적 자립.

Q7. 장비
맥북에 델모니터. JetBrains사 제품. IntelliJ, DataGrip, Workbench, 깃랩. 업소스

AWS. 놀이터

첫월급. 지인들과 삽겹살. 회식.

Q9. 우형 입사 계기

지인 때문.


=== [우.묻.다] 우아한형제들 개발자에게 묻는다. 밸런스게임편 1탄 2020.09.25
https://www.youtube.com/watch?v=anAfrII7LI8[[우.묻.다\] 우아한형제들 개발자에게 묻는다. 밸런스게임편 1탄 2020.09.25]

* 김지헌 - 결제서비스팀
* 이동욱 - 정산서비스팀
* 개발자 밸런스 게임?



=== 월요일 오후 1시 출근…주 4.5일 근무에도 연봉 4700만원 2019.03.28
http://news.chosun.com/misaeng/site/data/html_dir/2019/03/28/2019032800719.html[월요일 오후 1시 출근…주 4.5일 근무에도 연봉 4700만원 2019.03.28]

----
개발직군은 서류심사에서 온라인 코딩 테스트를 본다. 채용을 마칠 때까지 매주 수요일 홈페이지에 테스트 시간과 링크를 안내한다.
...
개발직군인 경우 질문 사항은 다음과 같다.
-서버장애에 대처해본 경험이 있는지?
-Pintos의 기본 구조에 대해 설명해보라.
-DB설계·도메인을 디자인해본 적이 있나?
-최근 C#버전이 몇이고 새롭게 추가한 기능은 무엇인가?
-사용해본 디자인 패턴에 대해 설명해보라.
----


* https://medium.com/@hairyss/%EC%9A%B0%EC%95%84%ED%95%9C-%ED%98%95%EC%A0%9C%EB%93%A4-%EB%A9%B4%EC%A0%91%EC%9D%84-%EB%B3%B4%EA%B3%A0-ffd62741f6[우아한 형제들 면접을 보고.. 2019.01.17]


* http://www.bloter.net/archives/322886[배달의민족 면접에서 듣게 되는 질문 65가지(2018년 ver.) 2018.10.26]

----
IT/인터넷 직군

8. 협동하며 일을 진행했던 경험은? 혹은 협업 시 문제가 생기면 어떻게 대처 했나?
9. 자신은 프론트엔드에 어울리는가 백엔드에 어울리는가?
10. 밤을 새서 코딩한 기억이 있나?
11. 업무를 수행하며 주로 활용하는 툴은 무엇인가?
12. 지난 프로젝트의 성과를 설명해 보라. 기억에 남는 업무가 있다면?
13. 프로젝트 진행 시 의사 결정 기준이 무엇인가?
14. 서비스를 개선해 본 경험을 말해 달라.
15. 스트링 손코딩을 해봐라.
16. 요즘 관심 있는 분야는 무엇인가?
17. 매일매일 하고 있는 공부가 있나? 공부 이외 하고 있는 일은?
18. 서버 장애에 대처해본 경험이 있는가?
19. 디비 설계 및 도메인 디자인 경험이 있는가?
20. 수강했던 수업 중 가장 재미있던 것은 무엇인가?
21. Pintos의 기본 구조에 대해 설명해 보라.
22. Thread와 Process의 차이점에 대해 설명해 보라.
23. Java는 어느 정도 다루나?
24. 자바 스크립트의 특징은 무엇이라고 생각하나?
25. 트래픽 과부하가 발생할 경우 어떻게 할 것인가?
26. 최신 기술 트렌드를 어떤 방법으로 쫓아 가는가?
27. 최근 C# 버전이 몇이며 새롭게 추가된 기능은 무엇인가?
28. Delegate, Lambda 식에 대해서 설명해 보라.
29. 생각나는 개발서에 대해서 인상 싶었던 부분을 이야기해보라
30. 사용해 본 디자인 패턴에 대해서 설명해 보라.
----
