= 우아한형제들 면접


== References

=== [우.묻.다] 우아한형제들 개발자에게 묻는다. 인터뷰편 1탄 2020.10.29
https://www.youtube.com/watch?v=g5sxpi0sJc4[[우.묻.다\] 우아한형제들 개발자에게 묻는다. 인터뷰편 1탄 2020.10.29]

김지헌. honeymon
이동욱. jojoldu

추천책

스프링 책

Real MySQL, 그림으로 배우는 Http & Network, 대규모 트래픽을 지탱하는

Java in Action
Spring in Action
토비의 스프링 3.1

Boot Spring Boot 출간

스프링 부트와 AWS로 혼자 구현하는...

Q2. 신기술 조사 방법

트위터 추천. 해외 개발자들이 트위터 많이 함. 그 사람들이 올린거 수집.

긱뉴스. xguru 권종혁님이 만든 서비스. RSS Feed 등록하거나 메일링

Q3. 공부하기 귀찮아지면

번아웃 해소 방법 이야기

Q4. 신입으로 돌아가면?

영어공부

Q5. 소프트웨어 스킬 어필

경청을 잘 해야됨. 질문의 의도를 정확하게 파악.

비개발 직군에게 설명하는 연습

Q6. 대학생. 맞지 않는 것 같다는 생각. 개발자분들도? 개발자가 되고자 했던 특별한 게기?

10년. 매일 그 생각. 새로운 적성 찾아봄.

웹툰. SNS. 싫어하지 않은거에서 경제적 자립.

Q7. 장비
맥북에 델모니터. JetBrains사 제품. IntelliJ, DataGrip, Workbench, 깃랩. 업소스

AWS. 놀이터

첫월급. 지인들과 삽겹살. 회식.

Q9. 우형 입사 계기

지인 때문.


=== [우.묻.다] 우아한형제들 개발자에게 묻는다. 밸런스게임편 1탄 2020.09.25
https://www.youtube.com/watch?v=anAfrII7LI8[[우.묻.다\] 우아한형제들 개발자에게 묻는다. 밸런스게임편 1탄 2020.09.25]

* 김지헌 - 결제서비스팀
* 이동욱 - 정산서비스팀
* 개발자 밸런스 게임?



=== 월요일 오후 1시 출근…주 4.5일 근무에도 연봉 4700만원 2019.03.28
http://news.chosun.com/misaeng/site/data/html_dir/2019/03/28/2019032800719.html[월요일 오후 1시 출근…주 4.5일 근무에도 연봉 4700만원 2019.03.28]

----
개발직군은 서류심사에서 온라인 코딩 테스트를 본다. 채용을 마칠 때까지 매주 수요일 홈페이지에 테스트 시간과 링크를 안내한다.
...
개발직군인 경우 질문 사항은 다음과 같다.
-서버장애에 대처해본 경험이 있는지?
-Pintos의 기본 구조에 대해 설명해보라.
-DB설계·도메인을 디자인해본 적이 있나?
-최근 C#버전이 몇이고 새롭게 추가한 기능은 무엇인가?
-사용해본 디자인 패턴에 대해 설명해보라.
----


* https://medium.com/@hairyss/%EC%9A%B0%EC%95%84%ED%95%9C-%ED%98%95%EC%A0%9C%EB%93%A4-%EB%A9%B4%EC%A0%91%EC%9D%84-%EB%B3%B4%EA%B3%A0-ffd62741f6[우아한 형제들 면접을 보고.. 2019.01.17]


* http://www.bloter.net/archives/322886[배달의민족 면접에서 듣게 되는 질문 65가지(2018년 ver.) 2018.10.26]

----
IT/인터넷 직군

8. 협동하며 일을 진행했던 경험은? 혹은 협업 시 문제가 생기면 어떻게 대처 했나?
9. 자신은 프론트엔드에 어울리는가 백엔드에 어울리는가?
10. 밤을 새서 코딩한 기억이 있나?
11. 업무를 수행하며 주로 활용하는 툴은 무엇인가?
12. 지난 프로젝트의 성과를 설명해 보라. 기억에 남는 업무가 있다면?
13. 프로젝트 진행 시 의사 결정 기준이 무엇인가?
14. 서비스를 개선해 본 경험을 말해 달라.
15. 스트링 손코딩을 해봐라.
16. 요즘 관심 있는 분야는 무엇인가?
17. 매일매일 하고 있는 공부가 있나? 공부 이외 하고 있는 일은?
18. 서버 장애에 대처해본 경험이 있는가?
19. 디비 설계 및 도메인 디자인 경험이 있는가?
20. 수강했던 수업 중 가장 재미있던 것은 무엇인가?
21. Pintos의 기본 구조에 대해 설명해 보라.
22. Thread와 Process의 차이점에 대해 설명해 보라.
23. Java는 어느 정도 다루나?
24. 자바 스크립트의 특징은 무엇이라고 생각하나?
25. 트래픽 과부하가 발생할 경우 어떻게 할 것인가?
26. 최신 기술 트렌드를 어떤 방법으로 쫓아 가는가?
27. 최근 C# 버전이 몇이며 새롭게 추가된 기능은 무엇인가?
28. Delegate, Lambda 식에 대해서 설명해 보라.
29. 생각나는 개발서에 대해서 인상 싶었던 부분을 이야기해보라
30. 사용해 본 디자인 패턴에 대해서 설명해 보라.
----


https://www.youtube.com/watch?v=JBS3H3PzI58['오늘 당신이 탈락한다면?' 임원의 대답은?ㅣ면접봅시다ㅣ우아한형제들 2021.03.21]

CTO 송재하. 작년 4월 1일 합류

김민태. 웹 개발자 그룹장. 개발자 역량. 복지. 5월이 되면 5년째

회사 소개? 좋은 음식을 먹고 싶은 곳에서 라는 비전을 가지고 음식 배댈과...

B마트, 배민상회, 딜리, 만화경

고마운분, 귀한분, ...

개발자 초봉 5300인데 더 올릴 거

주문만큼 갈아서? 주 35시간 근무.

개인의 성장과 문화...

가족을 챙겨라

35시간 넘어가면 보상해드림

우아한형제들 단점?

엄청나게 높은 프리퀀시. 트래픽 크고, 가용성 높아서 엔지니어링 챌린지

자영업자. 서비스가 작동을 안하게 되면 타격. 어깨가 무겁다.

개발자 경력직 200~300명

합격 꿀팁?

저희 회사 서비스에 대해서 애정이 있고 혹은 뭔가 같이 해보고 싶음. 회사에 대한 애정. 가산점.

배달음식 안시켜 먹고 써본적 없으면...

경력자를 뽑다 보니. 신입들 끌고 가 주실 경력. 기술적이거나 상황에 대해서 잘 이해시키고 설명해 줄 수 있는

회사 로열티 직무
협업 소통

기술. 잘 이해할 수 있도록 설명할 수 있는 역량.

어떤 기술이고 왜 이 기술을 선택했고 어떻게 응용해서 어떻게 썼다. 가산점

3. 성장성. 정체되어 있는 게 아니라 성장

1차 면접 때 기술 역량

2차 면접. 커리어와 성장 방향. 왜 우아한형제들에 들어오려 했는가

무한도전 당황 면접.

100만 원으로 스타트업을 시작한다면?

CTO. 스타트업 하지 않고 키우겠다.

탈락한다면 왜 탈락할까. 김민태. 26년간 한번도 탈락한 적이 없다.



https://www.youtube.com/watch?v=vcL81FAYgys[공고만 무려 60개! 역대급 개발자 채용입니다. 꼭 지원하세요. 2021.03.11]

회사 장점. 젋은 IT기업. 평균 연령 32살. 1000명 넘는 구성원.

50살 개발자도 있고 다양함.

젊은 개발자 많다 보니 평균 연령이 낮음.

단체상해보험. 본인, 배우자, 자녀, 양가 부모님까지 지원

자녀. 어린이집. 무료.

정원.

35시간 근무. 포괄임금제 폐지. 연장 근무 한 만큼 수당 지급. 35시간 넘으면 연장 근무로 인정.

야근 신청할 때 분 단위로 신청.

올해부터 크게 달라지는 거. 코로나 상관없이 주 2회 재택. 주 3회 출근.

재택근무 지원금. 하다못해 인터넷, 전기세, 수도세. 집에 있는 시간이 많다 보니. 월 10만원.

모든 직군. 신입 초봉. 12.5% 이상. 기존에 백엔드 개발자 5300.

장점. 회사가 급성장 하면서 해결해야 될 게 많음. 기술적인 도전거리.

회사에서 즐기는 분위기. 문제들을 계속 해결해 나가면서 레벨업 해야 됨.

'스타보다 팀워크'

다 같이 거기에 맞춰서 도와

유하늬. 테크 리쿠루터. 주로 개발자 채용 전담. 컴퓨터공학과 전공.

2021.2 기준 60개.
서버/백엔드, 프론트엔드, iOS/안드로이드, 데이터, 정보보안/인프라, PM/QA, ..

우수한 분이면 무조건 다 뽑겠다.

직군 9개

서버/백엔드가 많이 열려 있음. 자바 스프링 환경에서 운영 개발

프론트엔드. 기본삼대장 JS, HTML, CSS
TS, React선호

앱 개발자. 디자인 패턴 적용해. Reactive. ios swift, android kotlin 능숙

경력 3년 차 이상. 역량이 있으신 분이라면 충분히 가능.

서비스를 잘 운영할 수 있게 공통기술쪽으로. 뒷단. 정보보안/인프라 쪽은 AWS환경 선호

데이터 분야에서는 AI 머신러닝,

데이터 분석가, 데이터 과학자 모델링 경험. 파이썬, R

1. 입사지원
2. 서류전형 - 직무테스트[1]
3. 1차면접 - 실무진
4. 2차면접 - 임원진
5. 최종합격

각 전형은 일주일 정도로 잡고 있음.

빠르면 1개월 안에 전형 전체

서비스 운영 경험이 있으신 분 선호 서류 탈락의 빈도가 높음

두 번쨰. 코딩 테스트.

자소서 합격 팁. 자기소개. 시그니처 문항. 좋아하는 시나 소설, 노래, 영화

지원하는 시점에서 돌아보고.

어떤걸 하고 싶은지 생각을 녹여내

달려라 하니 노래로 썼었음

피해달라. 본인이 하셨던 업무 중점. 거기에 사용했던 기술 셋. 왜 그런 기술셋을 썼었는지? 불편했던 점? 이후 프로젝트에 개선할만한 점들. 요런것들 경력기술사항에 써주시면

어떤 가치를 중점?

협력을 얼마나 잘 하는지? 성장을 하기 위해 노력을 하는지?

개발자들은 고여있을 수 없는 직무. 스터디, 책을 읽는지 어필.

회사의 비전. 송파구에서 일을 더 잘하는 11가지 방법. 어떻게 성장했고 일을 하는지 이해하는데 도움.

본인이 어떻게...

동일 직무 떨어지면 6개월 쿨타임.

탈락 해도 다시 도전해서 입사하신 분도 있음.

