:hardbreaks:
= Ant Design - Form

Form 컴포넌트와 폼 내의 Form.Item 컴포넌트로 구성된다.

폼 내에서 각 입력필드는 `Form.Item` 컴포넌트로 감싸져야 한다. 이 컴포넌트를 사용하여 해당 필드에 대한 레이블, 규칙 및 기타 설정을 정의할 수 있다.

Rules 및 Validation: 폼 필드에 대한 규칙을 정의하여 유효성 검사를 수행할 수 있다. 예를 들어, 필드가 비어 있으면 오류 메시지를 표시하도록 설정할 수 있다.

Initial Values: 초기 값은 `initialValues` prop을 사용하여 설정할 수 있다. 이를 통해 폼이 처음 렌더링될 때 필드에 초기값을 설정할 수 있다.

onFinish 함수: `Form` 컴포넌트에는 `onFinish` prop을 통해 제출되었을 때 실행될 함수를 설정할 수 있다. 이를 사용하여 폼이 제출될 때 필요한 동작을 수행할 수 있다.

Dynamic Form Items: 필ㄷ를 동적으로 추가하거나 제거할 수 있다. 이는 동적으로 확장되거나 변경되는폼을 구현하는 데 유용함

Form Layout: 다양한 레이아웃을 지원한다. 수평, 수직, 그리드 레이아웃 등을 적용할 수 있다.

== Dynamic Form Items


== Form.useForm

https://ant.design/components/form[Form]

Hooks
Form.useForm

데이터 저장소를 유지하기 위해 Form 인스턴스를 생성.



.확인필요

https://react-hook-form.com/docs/useform 이랑 관련이 있나?

form을 쉽게 관리하기 위한 custom hook

useForm의 장점
* useForm은 전체 양식을 다시 렌더링하지 않고 변경된 필드만 다시 렌더링하여 최적의 성능을 제공한다.
* 내장된 유효성 검사 기능을 활용하여 필수 입력 항목을 간편하게 검사할 수 있다.



== Form Component

https://ant.design/components/form[Form]

.Properties

* colon: 레이블 뒤에 콜론(:)을 표시할지 여부를 결정한다. 기본값은 true이다.
* disabled: 폼을 비활성화할지 여부를 결정한다. 기본값은 false이다.
* component: 폼 렌더링 요소를 지정한다. 기본값은 form이다. false 이면 DOM 노드를 생성하지 말라.
* fields:
* form: form instance
* feedbackIcons:
* initialValues: 초기값. form 초기화나 reset시 사용된다.
* labelAlign:
* labelWrap: label이 wrap 될지 말지. 기본값 false.
* labelCol:
* layout:
* name: form name.
* preserve: 필드가 제거 되어도 필드값을 유지한다.
* requiredMark:
* scrollToFirstError:
* size:
* validateMessages:
* validateTrigger:
* wrapperCol:
* onFieldsChange: 필드가 변경될 때 호출되는 함수. (필드와 value 변경의 차이?)
* onFinish: form submit시 데이터 유효성 검사 통과 후 호출되는 함수.
* onFinishFailed: form submit시 데이터 유효성 검사 실패시 호출되는 함수.
* onValuesChange: value가 갱신될 때 호출되는 함수.


https://react-hook-form.com/docs/useform/form
와는 다른듯


== Form.Item Component

데이터 양방향 바인딩, 유효성 검사, 레이아웃 등을 위한 Form 필드 컴포넌트

.Properties
* colon:
* dependencies:
* extra:
* getValueFromEvent:
* getValueProps:
* hasFeedback:
* help:
* hidden:
* htmlFor:
* initialValue:
* label:
* labelAlign:
* labelCol:




== References

https://www.nextree.io/react-hook-form/[React Hook Form 2023.09.22]

useState를 사용하여 상태를 관리하면 해당 상태가 변경될 때마다 컴포넌트가 다시 렌더링 된다.

useState를 사용한 상태 관리는 해당 상태와 연관된 컴포넌트만 다시 렌더링 되는 것이 아니라 컴포넌트 전체가 다시 렌더링 될 수도 있다. 이는 다른 컴포넌트 부분에도 영향을 미쳐 예상치 못한 동작이 발생해 오류가 생길 수도 있다. 결국 불필요하게 렌더링되면 원치 않는 계산이 발생해 성능 저하를 초래한다.

useForm props 중 일부
* register: 입력값을 등록하거나 유효성 검사 규칙을 React Hook Form에 적용할 수 있다.
* handleSubmit: form 유효성 검사가 성공하면 form 데이터를 처리해준다.
* formState: 전체 form 상태(유효성, 변경 여부, 에러 메시지 등)에 대한 정보가 포함되어 있어 form 응용 프로그램과 사용자의 상호 작용을 추적하는 데 도움이 된다.

객체 필드들의 default 값을 defaultValues{} 객체를 이용해 설정

[source,javascript]
----
const {
    register,
    handleSubmit,
    formState: { errors },
} = useForm<InputField>({
    defaultValues: {
        name: '',
        age: 0,
    }
});
----

그리고 input component에서 register 함수를 호출하여 사용자의 입력값을 form에 등록하며 formstate를 활용해 필드 유효성 검사가 실패하는 경우 오류를 반환하도록 설정한다. 마지막으로 유효성 검사를 통과한 최종 데이터는 handleSubmit 함수를 통해 console에 출력되게 한다.

[source,javascript]
----
const onSubmit: SubmitHandler<InputField> = (data) => console.log(data);

return (
    <div className="App">
        <header className="App-header">
            <form onSubmit={handleSubmit(onSubmit)}>
                <input {...register('name', { required: true })} />
                {errors.name && <span>Named is required</span>}

                <input type='number' {...register('age', { required: true })} />
                {errors?.age && <span>Age is required</span>}
                <button onSubmit={() => onSubmit}>register</button>
            </form>
        </header>
    </div>
)
----

useForm은 전체 양식을 다시 렌더링하지 않고 변경된 필드만 다시 렌더링하여 최적의 성능을 제공. 더불어 내장된 유효성 검사 기능을 활용하여 필수 입력 항목을 간편하게 검사할 수 있다.

Controller

