:hardbreaks:
= Redux Middleware

== References
https://velog.io/@jminkyoung/TIL-10-React-Redux-middleware-%EB%9E%80-Feat.-redux-thunk[React - Redux Middleware 란? (Feat. redux-thunk) 2021.07.15]

https://react.vlpt.us/redux-middleware/[리덕스 미들웨어]

리덕스 미들웨어는 리덕스가 지니고 있는 핵심 기능. Context API 또는 MobX를 사용하는것과 차별화가 되는 부분

액션 -> 미들웨어 -> 리듀서 -> 스토어

리덕스 미들웨어를 사용하면 액션이 디스패치 된 다음, 리듀서에서 해당 액션을 받아와서 업데이트하기 전에 추가적인 작업을 할 수 있음

여기서 언급한 추가적인 작업들은 다음과 같은 것들이 있음
* 특정 조건에 따라 액션이 무시되게 만들 수 있음
* 액션을 콘솔에 출력하거나, 서버쪽에 로깅을 할 수 있음
* 액션이 디스패치 됐을 때 이를 수정해서 리듀서에서 전달되도록 할 수 있음
* 특정 액션이 발생했을 때 이에 기반하여 다른 액션이 발생되도록 할 수 있음
* 특정 액션이 발생했을 때 특정 자바스크립트 함수를 실행시킬 수 있음

보통 리덕스에서 미들웨어를 사용하는 주된 사용 용도는 비동기 작업을 처리 할 때임. 예를 들어 리액트 앱에서 우리가 만약 백엔드 API를 연동해야 된다면, 리덕스 미들웨어를 사용하여 처리하곤 함

리덕스 미들웨어는 누구든지 만들어서 사용 할 수 있지만 일반적으로는 리덕스 미들웨어 라이브러리를 설치하여 사용함. 비동기 작업에 관련된 미들웨어 라이브러리는 redux-thunk, redux-saga, redux-observable, redux-promise-middleware 등이 있음

redux-saga와 redux-observable의 경우엔 특정 액션을 모니터링 할 수도 있으므로, 특정 액션이 디스패치됐을때 원하는 함수를 호출하거나, 또는 라우터를 통해 다른 주소로 이동하는 것이 가능함.

이 이 튜토리얼에서는 미들웨어를 사용하여 비동기작업을 처리하는 방법을 배우게 될 떄, redux-thunk와 redux-saga만을 다루게 됨 (이 두 라이브러리가 가장 많이 사용됨)

이번 튜토리얼을 통하여 간단한 미들웨어를 직접 만들어보면서 미들웨어가 어떻게 작동하는지 알아봄. 그 다음에는 redux-logger 라이브러리를 사용하여 미들웨어 적용하는 방법을 알아봄. 그리고 redux-thunk 또는 redux-saga를 사용하는 비동기 작업을 효율적으로 처리하는 방법도 배워봄

