:hardbreaks:
= 이동욱 - 제어할 수 없는 것에 의존하지 않기

아무리 급해도 항상 80~90점짜리 소프트웨어를 일정 내 개발할 수 있는 방법

선택의 순간마다 고민 하는 사람
VS
원칙에 따라 빠르게 결정하고
중요한 것만 고민 하는 사람


제어할 수 없는 것에 의존하지 않기

현실 세계의 변화와 설계 사이의 결합도를 줄여야 한다.
전화번호를 식별자로 사용하는가?
자신의 힘으로 제어할 수 없는 속성에 의존하지 말라
- 실용주의 프로그래머 중

주민등록번호
절대 변하지 않을 것이라 믿고 의존했던 속성이었지만, 변경이 발생하여 대부분의 시스템의 주요키 변경이 발생

2014년 8월 7일부터 (법령근거없는) 주민등록번호 수집 요구 금지
- 2015.2.6 까지 유예기간 운영
- 오프라인 본인확인 마이핀(My-pin) 시행

외부에서 전달 받은 값은 절대 주요키로 선택하지 않는다.

SQL 보다는 애플리케이션에서 값을 다룬다
password(), encrypt(), ...

제어할 수 없는 것에 의존할 수록 변화에 쉽게 흔들리는 소프트웨어가 만들어진다.

== 제어할 수 없는 코드

현재 시간(now())은 제어할 수 없는 것

일요일에만 성공하는 테스트

jest의 모킹 하니 되었지만

날짜 라이브러리 (js-joda)가 교체가 된다면?
테스트 프레임워크 (jest) 가 교체가 된다면?
변화에 쉽게 흔들리는 소프트웨어

라이브러리를 바꾸고 싶은데 모든 테스트를 바꿔야 되는 문제가 발생함

== 제어할 수 있는 코드

Default Parameter로 제어할 수 없는 값을 주입 받는다

discount(now = LocalDateTime.now())


== 전염되는 제어할 수 없는 코드

여러 강의들 중 결제 금액 계산 결과가 100원이 넘는 것들만 골라서 PG 결제


제어할 수 없는 함수에 의존하는 모든 코드가 제어할 수 업는 코드가 됨

제어할 수 없는 것
외부 서비스
Modal

제어할 수 있는 것
결제 금액 계산
100원이상 걸러내기

제어할 수 없는 코드란 순수하지 않은 함수 혹은 객체

제어 하기 쉬운 - Business Logic
제어 하기 어려움 - UI, Data

== 제어할 수 없는 팀원

제어할 수 없는 것
우리 회사의 매출
우리 회사의 투자
높은 개발자 연봉
스타트업 전체의 권고사직

제어할 수 있는 것
? -> 팀원의 성장 환경


좋은 시니어 개발자 [.line-through]#채용# 사내 강연

좋은 시니어들의 노하우를 흡수
(발표하다가 팀에 반할 수도 있고...)

정기적인 외부 시니어 강연
필요한 노하우를 먼저 제시하는 팀원들

YY 컨퍼런스에서 발표하신 BB님께 여줘보고 싶은게 있어요

XX 회사의 리드로 계신 AA 님을 만나뵙고 싶어요

잦은 피드백을 줄 수 있는 환경

정적분석
테스트 코드
Lint, 코드 포맷팅

할 수 있는 것에만 집중
긍정적으로 상황 해석하기

수년간 160킬로미터 이상 떨어진 다른 학교에서
연습 경기를 해야 하는 팀의 감독이라면?

장소를 옮겨 가면서 홈경기를 치르면 원정경기에 강해질 것이다
다른 곳에서 시합할 때의 산만함과 혼란스러움에 익숙할 테니까
88연승의 비밀 중

제어할 수 없는 것에 거리두기
제어할 수 있는 것에 집중하기
