= QR 1.Competitive Submissions (7pts)

https://codingcompetitions.withgoogle.com/codejam/round/000000000043580a/00000000006d0a5c

== Problem
Note: 문제 statements의 중요한 부분은 "Reversort"와 "Reversort Engineering"이 마지막 문을 제외하고는 같다는 것입니다. 그렇지 않으면 문제를 독립적으로 해결할 수 있습니다(?)

Reversort는 공유한 정수 목록을 오름차순으로 정렬하는 알고리즘입니다. 알고리즘은 "Reverse"연산을 기반으로 합니다. 이 연산의 각 애플리케이션은 목록의 연속된 부분의 순서가 바뀝니다.

알고리즘의 의사코드는 다음과 같습니다.

----
  for i := 1 to length(L) - 1
    j := position with the minimum value in L between i and length(L), inclusive
    Reverse(L[i..j])
----

i - 1 반복 후, 목록의 포지션 1,2,...,i-1는 L의 가장 작은 요소들을 오름차순으로 포함합니다. i번째 반복동안 프로세스는 서브리스트를 i번째 위치 부터 현재 위치까지 뒤집습니다. 그것은 i번째 최소 요소를 i번째에 위치하게 만듭니다.

예를 들어, 4개 요소로 된 목록이 있고 알고리즘은 3번 반복합니다. L = [4,2,1,3]의 프로세스 과정이 있습니다.

1. i = 1, j = 3 -> L = [1,2,4,3]
2. i = 2, j = 2 -> L = [1,2,4,3]
3. i = 3, j = 4 -> L = [1,2,3,4]

알고리즘을 수행하는데 가장 비용이 많이 드는 부분은 설계가 Reverse 연산이라는 것입니다. 그러므로 각 반복의 비용을 위한 측정은 간단히 Reverse를 통과한 서브목록의 길이입니다. 그건은 j-i+1값입니다. 전체 알고리즘의 비용은 각 반복 비용의 합입니다.

위의 예제에서 반복 비용은 3, 1, 2입니다. 전체는 6입니다.

주어진 초기 목록을 이용해서 Reversort 수행 비용을 계산하세요.

== Input
첫 줄 T는 테이스 케이스의 개수.
T개의 테스트 케이스가 뒤따릅니다. 각 테스트 케이스는 2줄로 구성됩니다. 첫줄 N은 input 목록의 요소들입니다. 두번째 줄 N은 입력 목록 L의 요소들을 나타내는 고유한 정수 L1, L2, ..., LN입니다.

== Output
각 테스트 케이스는 Case #x: y로 출력합니다. x는 테스트 케이스 번호이고 1부터 시작합니다. y는 목록의 주저진 목록을 Reversort한 전체 비용입니다.

== Limits
시간 제한: 10초
메모리 제한: 1 GB

== Test Set 1 (Visible Verdict)
1 <= T <= 100
2 <= N <= 100
1 <= Li <= N, for all i.
Li != Lj, for all i != j.

