= 좋은 개발자

== 좋은 개발자란?
좋은 개발자란 무엇인가? 사람마다 생각하는 좋은 개발자는 다를 것이다. 어떤 개발자가 좋은 개발자인지 생각해본다.

나쁜 개발자?

기술적으로 뛰어난 역량을 가진 개발자.

커뮤니케이션 능력이 좋은 개발자.

일을 잘 이끌어 가는 개발자.

크게 개발 역량이 뛰어난 개발자가 있을 것이고 매니징을 잘 하는 개발자가 있을 것이다.

조화롭게 잘 하는 개발자도 있을 것이다.

모든 것을 완벽하게 잘 하는 개발자가 있을지는 모르겠다.

어떻게 해야 좋은 개발자가 될 수 있는지는 잘 모르겠다.

좋은 개발자라고 생각 되는 사람들을 보고 분석하고 따라하고 노력해보자.

꾸준히 노력하다 보면 지금보다는 더 나은 개발자가 되어 있지 않을까?



== 하광성

https://tech.kakao.com/2018/10/23/kakao-blind-recruitment-round-2[2019 카카오 블라인드 공채 2차 오프라인 코딩 테스트 문제 해설 2018.10.23]


https://www.slideshare.net/kwangswei/ss-30510586[손코딩뇌컴파일눈디버깅을 소개합니다. 2014.01.27]

* Communication. 머리 속에서 혼자 하지 말고 말로 표현하여 서로 토론하고 검증하기
* Question. 좋은 질뭉느 좋은 답을 이끌어낸다.
* Focusing. 자신의 생각은 잠시 내려놓고 현재 논의 중인 내용에 집중하기.
* Done is better than perfect. Small step. Time keeper

Triple sum. 숫자 리스트가 주어지고 3개의 수를 골라 합이 0이 되는 경우의 수를 반환하는 함수.

필요한 가정
시간/공간 복잡도 제한?
숫자의 범위는? 0도 포함?
숫자 리스트의 크기는 어느정도?
순서가 중요?
숫자는 중복이 가능?


* facebook: https://www.facebook.com/kwangswei
* tistory: https://kwangswei.tistory.com

== 정리
* https://junho85.pe.kr/1981[좋은 개발자란 - 배달의민족 CEO 김범준이 생각하는 좋은 개발자 2021.07.13]
* https://junho85.pe.kr/1982[좋은 개발자란 - 이미 정해져 있다. 태도의 중요성. 2021.07.14]

== References

https://www.facebook.com/hacker.golbin/posts/10159209972220040[좋은 개발자의 조건 2021.05.12]

https://sangminpark.blog/2021/05/11/%ec%bd%94%eb%8d%94/[코더]


1. 코딩능력
2. 겸손
3. 커뮤니케이션 능력


https://www.youtube.com/watch?v=2f-0BQ6T12M[개발자 고민 상담, "좋은 개발자와 일하고 싶다고? 근데 좋은 개발자는 무엇이냐?" 2019.11.05]

객체지향, 코드품질

적절한 시간안에 적절한 기능을 만들어내야

외부행사 발표하고, 커뮤니티 활동 열심히 하고

회사 업무에서 성과를 못내면 좋은 개발자?

새로운 기술 도입 꺼리고 보수적. 그런데 버그를 잘잡아. 노하우가 빠삭해.

단편적으로 볼 수 없는 거

주어진 상황에 따라 다르다

회사일도 잘 하고 지식 공유도 잘해. 그럼 좋은 개발자인가? 가정에 소흘하면? 좋은 개발자 의미가 있나? 좋은 인간? 좋은 부모? 내 삶은 회사에? 외부에 의미가 있는 건가?

일도 잘하고, 외부 활동도 잘하고, 집에서도 잘해. 그런데 건강이 안좋아.

일도 잘하고, 외부 활동도 열심히 하고, 건강하고, 가정 소흘하지 않은데 좋은 개발자인가? 삶의 의미를 찾지 않았으면? 내가 진짜로 만들고 싶었던 걸 못했어.


https://www.youtube.com/watch?v=TG9bpvGi2BE[괜찮은 프로그래머가 될 사람은 이미 정해져 있다. 2020.03.21]

잘 하는 사람
모르는 일 압박감.
될 때 까지 한다.

시키는 일만 하는 것이 아니고 의도를 파악하고 의도에 맞게끔

일을 잘 하는 사람의 특징.

1. 모르고 막막한 일이 있어도 포기하지 않고 끝까지 한다.
2. 일이 주어지면 본질이 무엇인지 판단을 한다. 시킨일만 하는 것이 아니고 의도를 파악한다.
3. 자기계발에 욕심이 있다.
4. 엄청 성칠하거나 똑똑하거나. 성실하면서 똑똑
5. 지식을 조립을 잘 한다.

책임감, 성실함, 똑똑함, 응용력
지능보다는 태도에 가깝다.

지식은 공부하면 느는데 태도는 정말 잘 안 변한다.

코딩을 잘 한다고 일을 잘 하는 것은 아니다.

조금만 꼼꼼하면 사전에 발견해서 해결할 수 있는 문제를 해결하지 않는다.

계속 발전하려는 의지

성실

똑똑

지식을 습득했을 때 조립을 잘 함

책임감, 성실함, 똑똑함, 응용력

일을 대하는 태도

지식은 늘지만 태도는 변하기 어려움.

좋은 학교 나오고 똑똑한데 일 마무리가 안되는 사람.

꼼꼼함이 있으면 되는데.

빵꾸 안나고 에러 안낼 수 있을텐데.

똑똑한데. 문제 생기면 담배 피러 나가기만 함.

연락 없이 일정 안지키냐. 카톡방 나가버림.

변하는 방법은 있다고 봄. 시작점. 나에게 문제가 있구나 인지. 책을 보거나. 남이 이야기 해주면 잘 새겨 듣거나. 명상을 해서 본인 스스로를 성찰하여 깨닫거나. 인지하고 변하는 사람은 계속 변함. 안변하는 살마은 끝까지 안변함. 남의 말을 안들음.

삶을 파괴 시킨 것. 분노. 게임중독. 20대 초. 3년간 일기 썼지만 안되서 때려치웠지만 20년 지나서 서서히 바뀜.

될 놈은 처음부터 된다. 될 놈은 그런 태도를 가지고 있음.


https://www.youtube.com/watch?v=PCkFeHJxJn4[생활습관을 고쳐야 좋은 엔지니어(프로그래머)가 된다 2017.08.17]

모든 걸 믿고 맡길 수 있다.

속도는 비슷한데 깔끔.

다른쪽을 시켜도 잘 함

일을 좋아함. 생활 자체가 일을 생각함. 관심있는 분야.

야근을 하지는 않아도 집에 와서 계속 생각. 이렇게 하면 나아지지 않을까. 술먹고 밥먹고 이야기 하는 동안에도 이렇게 하면, 저렇게 하면 좋지 않을까. 풀어가는 과정이 재미있다. 테크를 이야기 하며 즐거워 하는 것.

일을 돈으로 보는가. 좋아서 하는가.
