= 좋은 개발자가 되려면

* 어떤 개발자가 좋은 개발자?
** 유명한 개발자? 발표도 많이 하고 책도 쓰고
** 실력 있는 개발자? 굵직한 프로젝트를 성공적으로 이끌어 간 경력
** 생산성 높은 개발자 (드라마 )
* 좋은 개발자 보고 배우기
* 나쁜 개발자를 타산지석 삼기
* 수련 - 부족한 부분 개선
* 학습
** 공부
** 사이드 프로젝트
** 독서


== References

=== 능력 있는 개발자는 어떻게 알아볼 수 있나? by 황준식님 2017.01.18
https://okky.kr/article/370719[능력 있는 개발자는 어떻게 알아볼 수 있나? by 황준식님 2017.01.18]
https://docs.google.com/document/d/1_phA5XUszSmN7Ta-QHs4DxRz9_iu8YlhxpVjSGEbWcg/edit[원문]
https://www.facebook.com/groups/codingeverybody/permalink/1501967613177103[생활코딩]

우리나라 초중고급과 다름. 우리나라 옛날 등급제를 따르면 대학 나오고 경력 13년이면 특급.

드레퓌스 기술 습득 모형에서는 1%만 expert에 도달

https://zdnet.co.kr/view/?no=20141106211852[백발의 개발자가 되기 위한 커리어 패스 2014.11.07]
글에 의하면 슈퍼 개발자는 많이 / 빨리 만드는 사람이 아니라, 다른 사람의 실수 / 삽질을 사전에 막아내는 사람.

능력있는 개발자는
조직 전체로는 일을 효과적으로 할수 있도록 해주고,
개인에게는 빨리 실력을 키울수 있게 해줌.

능력있는 개발자는 Competent부터. Coach가 가능한 레벨. Competent 이상은 10~20%라고 생각

Competent를 찾아서 무조건 물고 늘어지라

책보고 디자인 패턴 세미나 이런게 아님. Competent사람 찾아서 더 배우기 위해서 노력하고, 이해 안가도 기술을 모방. 혼나고. 이해의 실마리 잡기. 같이 일 할 기회가 오면 그 일을 택함.

자신의 코드를 보여주는 것에 용기를 가지기.

자기 보다 윗줄인 Competent 구분할 방법.
여러분의 코드를 리뷰하여 고치게 해보라.

1시간쯤 고치게 하고 코드 리뷰 시킴.
코드 리뷰어가 왜 코드를 이렇게 작성했는지 의도를 알 수 있게, 코드 작성자에게 질문을 할수 있어야 함.
수정해서 나온 결과물이 교과서에서나 보던 그런 코드 같다면, 적어도 Competent

Competent. 교과서 내용 정도는 몸에 베여있음. 코칭을 할 수 있다는 것은 자기 몸이 교과서라는 의미.

Proficient. 직관적 레벨에서 결정을 내리기 때문에 Competent보다 더 빨리 고침.

코드리뷰

https://github.com/wonism/easy-map/blob/master/src/easy-map.js
지금은 이 코드는 없고

예전 코드 링크
https://github.com/wonism/easy-map/commit/df77d696ba231db5ee627b3f2974a47a49c1e228#diff-78c00f9c4deb5bc09a5c01aab1dd84ec9058490d6c15f3e75c5a3c91fadaebae

코드의 첫 인상은 Advanced Beginner가 작성한 것으로 보인다

멤버 변수 이름부터가 중복이 과함. prefix형태로 쓰였는데, 그런 반면에 같은 대상에 대한 데이터를 같이 묶는 (structure, class) 기법이 보이지 않음.

oop에서 Switch가 과하게 등장하면, 추상화 개념을 아직 적용못했다는 의미

7군데 switch (this.mapType)이 쓰였음.

함수 길이도 김.

함수들 마다 Switch가 다 들어가 있음.

문제 해결하는 루틴을 함수 하나 안에 주르륵 쓰고 있음. 체계적으로 계획을 세우는 함수 단위의 사고 적용을 잘 못한다고 평가할 수 있음.

markerNames와 Ids없애고 markers = []로 선언. Marker클래스는 name과 id를 가지게 함.

...

품이 많이 들어가는 작업은 Advanced Beginner가 거의 하고, Competent는 그걸 정리해서 수준을 끌어 올림


https://docs.google.com/document/d/1A10nVZVaqDx46zTvXVSxFV0dlmC-8q5yDWsdGoL6yNU[나는 어쩌다가 해외 개발사의 제의를 받았나?]


https://docs.google.com/document/d/1VDGXn6RsSM2-rOuF8e2KyG2ywZegJZFx1SpKxJOC630/edit[개인 프로필(과외)]


http://agile.egloos.com/4834009[1만 시간 법칙에 대한 오해 2009.03.22]
----
원래 연구에서는 시간 사용을 일, 놀이, 수련으로 나누었을 때 그 중 오로지 수련 시간의 누적만이 실제 퍼포먼스와 관련이 있더라는 발견을 했습니다.

따라서 개발자가 하루에 몇 시간 몰두해 일하냐로 따지지 말고, 하루에 몇 시간 오로지 수련(deliberate practice 특별히 자신의 기량을 높히기 위해 하는 수련 -- 자신이 이미 잘하는 걸 하는 것이 아니라 부족한 부분을 개선하기 위해 고안한 수련을 하는 것)을 위해 시간을 쓰느냐로 따져야 합니다.
----


https://www.freecodecamp.org/news/how-to-become-a-great-software-developer/[How to Become a Great Software Developer [with Actionable Tips\] 2021.01.12]
