= 좋은 개발자가 되려면

== References
* http://blog.lastmind.io/archives/593[Dreyfus Model 2008.12.02]

관리자의 입장에서 가장 예뻐 보이는 동료

'주어진 업무를 수행할 떄, 업무의 목표가 무엇인지 정확히 이해하고 수행하는 사람'
'상위 조직의 목표까지 고려해서, 원래 업무의 방향을 수정하거나, 업무의 우선순위를 조정하거나, 적절한 새로운 업무를 추진할 수 있는 사람'
관리가 필요하지 않는 사람이 바로 관리자의 이상형

A. 지시하지 않은 세부 사항까지 알아서 척척 처리해, 손이 닿지 않는 곳의 가려움에서 벗어나는 기쁨을 안겨 줌
B. 완료했다는 일이 처음부터 업무를 처리할 방식을 세세하게 다시 설명해 주어야 할 정도로 엉망
왜? B는 업무 시간에 집중해서 성실하게 일하며 책임감도 높다.

둘 사이에는 업무를 대하고 처리하는 방식에는 본질적인 차이가 있다.

Dreyfus Model

드라이퍼스 모델 (Dreyfus Model)
철학자 드라이퍼스 (Hubert L. Drefus)가 그의 저서 Mind Over Machine의 도입부에서 제안한 기술 습득의 5단계 모델.
Andy Hunt의 Pragmatic Thinking & Learning의 2장에 소개되어 있다.

Stage 1: Novices

Stage 2: Advanced Beginners

Stage 3: Competent

Stage 4: Proficient

Stage 5: Expert

=== 능력 있는 개발자는 어떻게 알아볼 수 있나? by 황준식님 2017.01.18
https://okky.kr/article/370719[능력 있는 개발자는 어떻게 알아볼 수 있나? by 황준식님 2017.01.18]
https://docs.google.com/document/d/1_phA5XUszSmN7Ta-QHs4DxRz9_iu8YlhxpVjSGEbWcg/edit[원문]
https://www.facebook.com/groups/codingeverybody/permalink/1501967613177103[생활코딩]

우리나라 초중고급과 다름. 우리나라 옛날 등급제를 따르면 대학 나오고 경력 13년이면 특급.

드레퓌스 기술 습득 모형에서는 1%만 expert에 도달

https://zdnet.co.kr/view/?no=20141106211852[백발의 개발자가 되기 위한 커리어 패스 2014.11.07]
글에 의하면 슈퍼 개발자는 많이 / 빨리 만드는 사람이 아니라, 다른 사람의 실수 / 삽질을 사전에 막아내는 사람.

능력있는 개발자는
조직 전체로는 일을 효과적으로 할수 있도록 해주고,
개인에게는 빨리 실력을 키울수 있게 해줌.

능력있는 개발자는 Competent부터. Coach가 가능한 레벨. Competent 이상은 10~20%라고 생각

Competent를 찾아서 무조건 물고 늘어지라

책보고 디자인 패턴 세미나 이런게 아님. Competent사람 찾아서 더 배우기 위해서 노력하고, 이해 안가도 기술을 모방. 혼나고. 이해의 실마리 잡기. 같이 일 할 기회가 오면 그 일을 택함.

자신의 코드를 보여주는 것에 용기를 가지기.

자기 보다 윗줄인 Competent 구분할 방법.
여러분의 코드를 리뷰하여 고치게 해보라.

1시간쯤 고치게 하고 코드 리뷰 시킴.
코드 리뷰어가 왜 코드를 이렇게 작성했는지 의도를 알 수 있게, 코드 작성자에게 질문을 할수 있어야 함.
수정해서 나온 결과물이 교과서에서나 보던 그런 코드 같다면, 적어도 Competent

Competent. 교과서 내용 정도는 몸에 베여있음. 코칭을 할 수 있다는 것은 자기 몸이 교과서라는 의미.

Proficient. 직관적 레벨에서 결정을 내리기 때문에 Competent보다 더 빨리 고침.

코드리뷰

https://github.com/wonism/easy-map/blob/master/src/easy-map.js
지금은 이 코드는 없고

예전 코드 링크
https://github.com/wonism/easy-map/commit/df77d696ba231db5ee627b3f2974a47a49c1e228#diff-78c00f9c4deb5bc09a5c01aab1dd84ec9058490d6c15f3e75c5a3c91fadaebae

코드의 첫 인상은 Advanced Beginner가 작성한 것으로 보인다

멤버 변수 이름부터가 중복이 과함. prefix형태로 쓰였는데, 그런 반면에 같은 대상에 대한 데이터를 같이 묶는 (structure, class) 기법이 보이지 않음.

oop에서 Switch가 과하게 등장하면, 추상화 개념을 아직 적용못했다는 의미

7군데 switch (this.mapType)이 쓰였음.

함수 길이도 김.

함수들 마다 Switch가 다 들어가 있음.

문제 해결하는 루틴을 함수 하나 안에 주르륵 쓰고 있음. 체계적으로 계획을 세우는 함수 단위의 사고 적용을 잘 못한다고 평가할 수 있음.

markerNames와 Ids없애고 markers = []로 선언. Marker클래스는 name과 id를 가지게 함.

...

품이 많이 들어가는 작업은 Advanced Beginner가 거의 하고, Competent는 그걸 정리해서 수준을 끌어 올림


https://docs.google.com/document/d/1A10nVZVaqDx46zTvXVSxFV0dlmC-8q5yDWsdGoL6yNU[나는 어쩌다가 해외 개발사의 제의를 받았나?]


https://docs.google.com/document/d/1VDGXn6RsSM2-rOuF8e2KyG2ywZegJZFx1SpKxJOC630/edit[개인 프로필(과외)]

=== 백발의 개발자가 되기 위한 커리어 패스 2014.11.07
https://zdnet.co.kr/view/?no=20141106211852[백발의 개발자가 되기 위한 커리어 패스 2014.11.07]

드라이퍼스 모델

.초급자(Novice)
언어와 개발 도구에 대해 경험이 전무한 초급 개발자. 매뉴얼을 따라 결과를 만들어 내지만 혼자서 창의적으로 코드를 작성하기 어려움

.초중급자(Advanced Beginner)
매뉴얼 없이 어느정도 개발이 가능한 단계. 어려운 로직이 아닌 범위 안에서 자유롭게 코드를 작성할 수 있는 단계.

.능숙자(Competent)
언어와 툴에 대해서 모두 익숙해진 단계. 어떤 프로그램 로직이라도 원하는 결과물을 만들어 내는 것이 가능.
국내의 경우 품질보다 결과를 더 중시하는 문화 때문에 숙련자로 성장해야 된다는 필요를 느끼지 못하는 경우가 많음. 5~7년이 지나면 개발자 레벨이 평준화된다고 이야기하는 것을 종종 듣는 것과 같은 맥락.

.숙련자(Proficient)
만드는 결과물이 같지만 그것을 어떻게 만들었는지에 대해서는 차이. 보다 많은 예외 상황들을 고려하고 향후에 확장될 수 있는 가능성들을 검토해 보다 언어적으로는 객체지향적이고 또 관점지향적인 설계가 가능. 더불어 시스템이나 플랫폼적인 설계도 가능하게 되는 단계.
많은 개발 패턴들을 알고 있고 실제 어떤 상황에서 적용함녀 좋고 안 좋은지에 대한 이해.

.전문가(Expert)
외국에서는 개발자들의 코드를 리뷰하는 하키텍트. 소프트웨어 품질 관리.
숙련자들이 할 수 있는 실수들을 줄여줄 수 있는 능력을 가지고 있어야 함.
그들이 하게 되는 실수들을 미리 경험해보고 다양한 경우에 대한 설계 노하우를 갖고 조언할 수 있어야 함.

