= 드라이퍼스 모델 - The Dreyfus Model of Skill Acquisition

http://egloos.zum.com/smile/v/1153847[드라이퍼스 모델(The Dreyfus Model of Skill Acquisition)]

Table 2. Model of Debugging Abilities and Habits.

Stage, Debugging Abilities and Habits.

.Novice
* Lacks debugging skills
* Repeats the same types of defects frequently throughout a program
* Debugs programs haphazardly instead of following a plan
* Spends considerable amounts of time on debugging
* Gives up easily and depends on others for assistance

.Advanced Beginner
* Develops debugging skills through experience; recognizes symptoms of previously experienced defects
* Repeats the same types of defects occasionally throughout a program
* Begins adapting approaches to debugging based on prior successes and failures
* Attempts less familiar debugging techniques only as a last resort
* Relies to some extent on others for assistance

.Competent
* Knows a variety of debugging techniques
* Approaches debugging systematically; evaluates the situation to determine which techniques to use
* Alternates between techniques when certain techniques are not effective
* Identifies most defects independently

.Proficient
* Sees debugging as part of program development as a whole
* Develops skills in other areas of program development to facilitate debugging
* Optimizes decision-making abilities and approaches to debugging
* Asks others for assistance rarely and assists others

.Expert
* Approaches debugging intuitively due to extensive experience; debugging is second-nature
* Identifies complex and/or unfamiliar defects successfully
* Asks others for assistance rarely and assists others

== References

=== Dreyfus Model 2008.12.02
* http://blog.lastmind.io/archives/593[Dreyfus Model 2008.12.02]

관리자의 입장에서 가장 예뻐 보이는 동료

'주어진 업무를 수행할 떄, 업무의 목표가 무엇인지 정확히 이해하고 수행하는 사람'
'상위 조직의 목표까지 고려해서, 원래 업무의 방향을 수정하거나, 업무의 우선순위를 조정하거나, 적절한 새로운 업무를 추진할 수 있는 사람'
관리가 필요하지 않는 사람이 바로 관리자의 이상형

A. 지시하지 않은 세부 사항까지 알아서 척척 처리해, 손이 닿지 않는 곳의 가려움에서 벗어나는 기쁨을 안겨 줌
B. 완료했다는 일이 처음부터 업무를 처리할 방식을 세세하게 다시 설명해 주어야 할 정도로 엉망
왜? B는 업무 시간에 집중해서 성실하게 일하며 책임감도 높다.

둘 사이에는 업무를 대하고 처리하는 방식에는 본질적인 차이가 있다.

Dreyfus Model

드라이퍼스 모델 (Dreyfus Model)
철학자 드라이퍼스 (Hubert L. Drefus)가 그의 저서 Mind Over Machine의 도입부에서 제안한 기술 습득의 5단계 모델.
Andy Hunt의 Pragmatic Thinking & Learning의 2장에 소개되어 있다.

Stage 1: Novices

Stage 2: Advanced Beginners

Stage 3: Competent

Stage 4: Proficient

Stage 5: Expert


=== 백발의 개발자가 되기 위한 커리어 패스 2014.11.07
https://zdnet.co.kr/view/?no=20141106211852[백발의 개발자가 되기 위한 커리어 패스 2014.11.07]

드라이퍼스 모델

.초급자(Novice)
언어와 개발 도구에 대해 경험이 전무한 초급 개발자. 매뉴얼을 따라 결과를 만들어 내지만 혼자서 창의적으로 코드를 작성하기 어려움

.초중급자(Advanced Beginner)
매뉴얼 없이 어느정도 개발이 가능한 단계. 어려운 로직이 아닌 범위 안에서 자유롭게 코드를 작성할 수 있는 단계.

.능숙자(Competent)
언어와 툴에 대해서 모두 익숙해진 단계. 어떤 프로그램 로직이라도 원하는 결과물을 만들어 내는 것이 가능.
국내의 경우 품질보다 결과를 더 중시하는 문화 때문에 숙련자로 성장해야 된다는 필요를 느끼지 못하는 경우가 많음. 5~7년이 지나면 개발자 레벨이 평준화된다고 이야기하는 것을 종종 듣는 것과 같은 맥락.

.숙련자(Proficient)
만드는 결과물이 같지만 그것을 어떻게 만들었는지에 대해서는 차이. 보다 많은 예외 상황들을 고려하고 향후에 확장될 수 있는 가능성들을 검토해 보다 언어적으로는 객체지향적이고 또 관점지향적인 설계가 가능. 더불어 시스템이나 플랫폼적인 설계도 가능하게 되는 단계.
많은 개발 패턴들을 알고 있고 실제 어떤 상황에서 적용하면 좋고 안 좋은지에 대한 이해.

.전문가(Expert)
외국에서는 개발자들의 코드를 리뷰하는 하키텍트. 소프트웨어 품질 관리.
숙련자들이 할 수 있는 실수들을 줄여줄 수 있는 능력을 가지고 있어야 함.
그들이 하게 되는 실수들을 미리 경험해보고 다양한 경우에 대한 설계 노하우를 갖고 조언할 수 있어야 함.


