= 좋은개발자가 되려면 - 커뮤니케이션


== 커뮤니케이션 능력을 향상시키려면?
* 독서
* 좋은 사람

* 용어사전
* 글쓰기

== References

https://medium.com/code-states/good-developer-1-%EC%A2%8B%EC%9D%80-%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98-5%EA%B0%80%EC%A7%80-%EA%B8%B0%EC%A4%80-b4b9f166caf7[Good Developer 1 | 좋은 개발자의 5가지 기준 2018.04.14]

코드, 생산성, 커뮤니케이션, 학습, 관리 능력



https://medium.com/code-states/good-developer-2-%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98-%EC%9E%98%ED%95%98%EB%8A%94-%EA%B0%9C%EB%B0%9C%EC%9E%90%EA%B0%80-%EB%90%98%EB%8A%94-%EB%B0%A9%EB%B2%95-76e78da0ffc2[Good Developer 2 | 커뮤니케이션 잘하는 개발자가 되는 방법 2018.04.14]

커뮤니케이션이 월활하지 않아 개발 업무에 차질이 생기는 일이 다반사. 원활한 커뮤니케이션은 막혔던 문제를 훨씬 더 빠른 속도로 풀릴 수 있게끔 만든다.

대화의 목적과 목표를 분명히 하라
대화가 끝난 후에는 반드시 대화에서 얻어낸 결과물들을 테스크로 전환하고 각자에게 배분하라!

논쟁의 지점을 분명히 하라!
용어를 분명히 하라!


https://medium.com/code-states/good-developer-3-%EB%82%98%EC%81%9C-%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98-11%EA%B0%80%EC%A7%80-%EC%8A%B5%EA%B4%80-14c9702bd88[Good Developer 3 | 나쁜 개발자의 11가지 습관 2018.04.19]

* 습관 1: 코드 리뷰가 없다.
* 습관 2: 문서화를 하지 않는다.
* 습관 3: 커뮤니케이션 향상에 관심이 없다.
* 습관 4: 업무 공유가 되지 않는다.
* 습관 5: 코드의 복붙(복사 후 붙여넣기)가 '일상화'되어 잇다.
* 습관 6: 자신의 부족한 점을 드러내지 않는다.
* 습관 7: 새로운 기술을 익히는데 시간을 투자하지 않는다.
* 습관 8: 자신의 개발 환경에서 벗어나지 않는다.
* 습관 9: 자신이 맡은 개발과 관련된 비즈니스를 이해하지 않는다.
* 습관 10: 개발에 대한 자신만의 장기적인 목표가 없다.
* 습관 11: 자신의 나쁜 개발 습관에 관심이 없다. (습관은 아니지만....)


https://medium.com/code-states/%EB%8D%94-%EC%9D%B4%EC%83%81%EC%9D%98-%EC%84%A4%EB%AA%85%EC%9D%80-%ED%95%84%EC%9A%94-%EC%97%86%EB%8B%A4-fa2308305ae7[Good Developer 4 | 학습하는 개발자 — 고농축 학습 자료 꿀팁 2018.04.28]



https://zdnet.co.kr/view/?no=20160425094045[개발자의 생명은 커뮤니케이션 능력 2016.04.25]

프로그래머: 코딩을 통해서 컴퓨터에게 원하는 일을 시킬 수 있다. 학교 숙제, 취미로 코딩, 혼자 오픈소스 코드 만들어 내는 사람은 프로그래머 혹은 해커에 가깝다
개발자: 기업이나 큰 프로젝트에 속해서 다른 사람과 협업을 통해서 코드를 만들어낸다.

프로그래머에게 생명은 코딩 기술이고 개발자의 생명은 커뮤니케이션 능력

개발자에게 코딩 능력은 기본

- 명확하지 않은 많은 이야기 속에서 지엽적인 것을 걸러내고 본질을 파악하는 능력
- 복잡한 논리나 추상적인 개념을 상대방이 이해할 수 있게 설명하는 능력
- 타인의 감정을 이해하는 공감능력

커뮤니케이션 능력을 키우는 방법

- 독서: 컴퓨터를 끄고, 전화를 내려놓고 호흡이 긴 독서를 해야 한다.
- 좋은 사람: 감정이 소모되거나 자기를 자기답게 만들어주지 않는 사람은 만날 필요가 없다.

* 논쟁의 지점을 분명히 하기
* 용어를 분명히

* 나와 상대방의 커뮤니케이션 스타일 이해
* 동료에게 자신의 커뮤니케이션에 있어서 부족한 점을 솔직히 말해달라고 부탁
* 동료와 좋은 관계 형성

대화가 커뮤니케이션의 전부가 아니다. 도구를 잘 쓰자

* ASANA: 자신과 동료의 업무를 리스트화하고 체크
* 구글 캘린더: 일정 공유


https://www.reimaginer.me/entry/%EC%A2%8B%EC%9D%80-%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98-%EB%8D%95%EB%AA%A9[좋은 개발자의 덕목 세가지 2018.07.18]
우아한 형제들 지원할 때 썼다는 내용
