= JPA 소개

https://www.inflearn.com/course/ORM-JPA-Basic/lecture/21683?tab=curriculum

== JPA - Java Persistence API

== JPA?
- Java Persistence API
- 자바 진영의 ORM 기술 표준

== ORM?
- Object-relational mapping(객체 관계 매핑)
- 객체는 객체대로 설계
- 관계형 데이터베이스는 관계형 데이터베이스대로 설계
- ORM 프레임워크가 중간에서 매핑
- 대중적인 언어에는 대부분 ORM 기술이 존재

== JPA는 애플리케이션과 JDBC 사이에서 동작

== JPA 동작 - 저장
쿼리를 JPA가 만들어줌

패러다임 불일치 해결

== JPA 동작 - 조회


== JPA 소개
EJB - 엔티티 빈(자바 표준)
- 기술이 너무 아마추어적
- 인터페이스 많이
- 성능도 너무 안나옴

하이버네이트 (오픈 소스)
- 게빈킹. 내가 만들고 말지
- 거친 오픈 소스

JPA(자바 표준)
- 자바진영에서 반성
- 게빈킹을 데려다가 하이버네이트 복붙하듯이 만든게 JPA
- 다듬고 용어정리 표준스펙

== JPA는 표준 명세
- JPA는 인터페이스의 모음
- JPA 2.1 표준 명세를 구현한 3가지 구현체
- 하이버네이트, EclipseLink, DataNucleus

80~90%는 하이버네이트


EJB에 분노한 또 다른 개발자 스프링 프레임워크 만들어냄

== JPA 버전
- JPA 1.0(JSR 220) 2006년: 초기 버전. 복합 키와 연관과계 기능이 부족
- JPA 2.0...
- JPA 2.1...

== JPA를 왜 사용해야 하는가?
- SQL 중심적인 개발에서 객체 중심으로 개발
- 생산성
- 유지보수
- 패러다임의 불일치 해결
- 성능
- 데이터 접근 추상화와 벤더 독립성
- 표준

== 생산성 - JPA와 CRUD
- 저장: jpa.persist(member)
- 조회: Member member = jpa.find(memberId)
- 수정: member.setName("변경할 이름")
- 삭제: jpa.remove(member)

자바 컬렉션에 넣다 뺐다 하듯이 DB를 사용한다.

== 유지보수 - 기존: 필드 변경시 모든 SQL 수정
연락처 추가해 달라

업데이트하는거 놓치고 버그 픽스 올라오고

JPA를 사용한다고 가정하면 DB컬럼추가 하고 객체에 추가 하면 됨. 쿼리 신경 쓸 필요 없음.

== JPA와 패러다임의 불일치 해결
1. JPA와 상속
2. ..
3. ...
4. ...

== JPA와 상속

== JPA와 상속 - 저장

개발자가 할일
jpa.persist(album);

나머진 JPA가 처리
INSERT INTO ITEM ...
INSERT INTO ALBUM ...

== JPA와 상속 - 조회

개발자가 할일
Album album = jpa.find(Album.class, albumId);

나머진 JPA가 처리
SELECT I.*, A.*
FROM ITEM I
JOIN ALBUM A ON I....

== JPA와 연관관계, 객체 그래프 탐색

연관관계 저장
member.setTeam(team);
jpa.persist(member);

객체 그래프 탐색
Member member = jpa.find(Member.class, memberId);
Team team = member.getTeam();

== 신뢰할 수 있는 엔티티, 계층

----
class MemberService {
  ...
  public void process() {
    Member member = memberDAO.find(memberId);
    member.getTeam(); // 자유로운 객체 그래프 탐색
    member.getOrder().getDelivery();
  }
}
----

== JPA와 비교하기
----
String memberId = "100";
Member member1 = jpa.find(Member.class, memberId);
Member member2 = jpa.find(Member.class, memberId);

member1 == member2; // 같다.
----

동일한 트랜잭션에서 조회한 엔티티는 같음을 보장

어떻게 가능한지는 강의 진행하면서 뒤에

== JPA의 성능 최적화 기능
1. 1차 캐시와 동일성(identity) 보장
2. 트랜잭션을 지원하는 쓰기 지연(transactional write-behind)
3. 지연 로딩(Lazy Loading)

== 1차 캐시와 동일성 보장
1. 같은 트랜잭션 안에서는 같은 엔티티를 반환 - 약간의 조회 성능 향상
2. DB Isolation Level이 Read Commit이어도 애플리케이션에서 Repeatable Read 보장

----
String memberId = "100";
Member m1 = jpa.find(Member.class, memberId); // SQL
Member m2 = jpa.find(Member.class, memberId); // 캐시

println(m1 == m2) // true
----
SQL 1번만 실행

== 1차 캐시와 동일성 보장
1. 같은 트랜잭션 안에서는 같은 엔티티를 반환 - 약간의 조회 성능 향상
2. DB Isolation Level이 Read Commit이어도 애플리케이션에서 Repeatable Read 보장

----
String memberId...
----

== 트랜잭션을 지원하는 쓰기 지연 - INSERT

1. 트랜잭션을 커밋할 때까지 INSERT SQL을 모음
2. JDBC BATCH SQL 기능을 사용해서 한번에 SQL 전송

----
transaction.begin(); // 트랜잭션 시작

em.persist(memberA);
em.persist(memberB);
em.persist(memberC);
// 여기까지 INSERT SQL을 데이터베이스에 보내지 않는다.

// 커밋하는 순간 데이터베이스에 INSERT SQL을 모아서 보낸다.
transaction.commit(); // 트랜잭션 커밋
----

== 트랜잭션을 지원하는 쓰기 지연 - UPDATE

...


== 지연 로딩과 즉시 로딩
- 지연 로딩: 객체가 실제 사용될 떄 로딩
- 즉시 로딩: JOIN SQL로 한번에 연관된 객체까지 미리 조회

지연 로딩

----
Member member = memberDAO.find(memberId); // SELECT * FROM MEMBER
Team team = member.getTeam();
String teamName = team.getName(); // SELECT * FROM TEAM
----

즉시 로딩

----
Member member = memberDAO.find(memberId); // SELECT M.*, T.* FROM MEMBER JOIN TEAM ...
Team team = member.getTeam();
String teamName = team.getName();
----

== ORM은 객체와 RDB 두 기둥위에 있는 기술

