:hardbreaks:

= garden7

== mongodb
----
docker run --name mymongo -p 127.0.0.1:27017:27017 -d mongo
----

----
docker start mymongo
mongosh
use garden7
----

== python 버전
기존 처럼 python 3.7 사용. 버전업 하려니 힘들 거 같아서 보류.
osx python3.7이 맛이 가서 다시 설치
----
$ brew install python@3.7
----


== 소스코드
garden6의 코드 복붙 후 garden6로 된 부분을 garden7로 변경

----
pip install -r requirements.txt
----


== pycharm 설정
Preferences -> Django

Enable Django Support

Settings: garden7/settings.py

=== interpreter
앞서 설치한 python3.7 로 지정해서 venv를 만든다.

/usr/local/opt/python@3.7/bin/python3.7

== slack
예전 링크 들어가보니 뭐가 뭔지 모르겠음. 어찌저찌 누르다 보니 앱생성
https://api.slack.com/apps/A02M9AZB5FF

OAuth & Permissions에 가서

Scope
* channels:history
* channels:read
* users:read

추가 하고 Install to Workspace

봇토큰이 필요한데 xoxb로 시작함.

#commit 방에서
/invite @garden7
으로 봇 초대

Basic Information -> App-Level Tokens에서 Generate Token

Token Name: attendance
권한 scope추가.
connections:write
authorization:read

토큰이 생성된다. ... 기존이랑 모양이 좀 다른데 맞나 모르겠다.

config.ini 설정
* SLACK_API_TOKEN = 생성한 토큰
* CHANNEL_ID = apps/뒤에 있는 값

== 도메인
* https://www.gabia.com/
* A 레코드 추가. garden7

== 구글 애널리틱스. Google Analytics
* Admin 페이지 가서 Create Property로 추가
* property name: garden7
* Advanced 설정에서 Create a Universal Analytics property

tracking code에 내용 복붙해서 google_analytics.html에 설정

... 진행중
