= 기술면접

== 구글 기술면접(Technical Interview) 재연 2012.11.07
https://www.youtube.com/watch?v=BF3FLDAzWxo[구글 기술면접(Technical Interview) 재연 2012.11.07]

* 인사
* 이력서. 가장 깊었던 일은? 생략
* 한시간 정도. 입력으로 두개의 단어가 주어 졌을 때 아나그램이면 true 아니면 false 리턴
* (질문) 아나그램이 뭘 뜻하는지?
* (설명) tab, bat단어는 서로 아나그램. 철자의 구성이 같고 순서만 다른 경우 아나그램.
* (확인) 똑같은 같은데 알파벳 순서가 바뀐게 아나그램이죠?
* 모든 알파벳 순서 조합으로 비교 해 보면 될 거 같다.
* 계산량?
* 모든 경우 단어 길이가 n일 때 n팩토리얼. 비교가 빨리 끝날 수도 있지만 n팩토리얼 만큼.
* n팩토리얼이면 계산량이 많아질텐데 효율적인 방법 없을지?
* 단어안의 철자의 순서 의미 없으니 양쪽다 순서를 통일해서 비교. 알파벳순으로 소팅해서 소팅된 두 단어를 비교하면 되겠음.
* 좋은 방법이네요. 그 경우 계산량은?
* 소팅하는데 nlogn 비교는 n이니 nlogn이면 되겠음.
* 코드는 c++?
* 편하신 랭귀지로 작성
배열은 char 배열로 해도 될지? 네
input 받은거 배열 바꿔도 될지? 네
라이브러리 써도 될지? 네

[source,cpp]
----
bool isAnagram(char *a, int a_len,
char *b, int b_len) {
  qsort(a, a_len);
  qsort(b, b_len);
  return strcmp(a, b) == 0;
}
----
실제로 함수가 잘 동작하는지 확인하려면?

bat, tab 되어야 될 거 같고
google, glegoo, gelogo 몇개 해보고
gggleo, go 해보고

함수를 좀 더 옵티마이즈? 비교를 하지 않아도 되는 경우가 있을 거 같은데

길이가 다르면 바로 끝낼 수 있음
----
if (a_len != b_len) return false;
----
수고 하셨습니다.

긴시간 수고 많으셨고요. 구글이나 구글 서울오피스에대해 궁금한점은?

밖에서 봤을 때 일하기 좋고 열정적으로 일하는 이미지. 오래 일해 보신분의 경험으로 봤을 때 어떤지? 오래 지났지만 여전히 벤처같이 즐겁게 일하는지?

밖에서 보는 이미지와 크게 다르지 않음. 최대한으로 할 수 있게 배려. 열심히 일할 수 있는 환경이 갖춰져 있다.



이렇게 가정해도 될지. 라이브러리를 사용해도 될지. 등 본인 마음대로 하는 것이 아니고 생각을 이야기 하면서 해결해 나가는 과정이 핵심. Brute force부터 차근차근 장단점 이야기 하면서 알고리즘을 개선시켜 나감.


== References
=== 배민, 스타트업 기술면접 공개! - 대표 질문 3가지! 2021.04.06
https://www.youtube.com/watch?v=3ArYMq5AomI[배민, 스타트업 기술면접 공개! - 대표 질문 3가지! 2021.04.06]

호돌맨. 신입. 진정성. 부트캠프. 토이프로젝트. 블로그에 내용 정리

향로. Ruby ORM. fetchJoin, 영속성 컨텍스트 다른 점

equals(), hashCode()가 무슨 메서드고 어떨 때 써야하는지


로그인 기능 구현

세션

HttpSession 클래스

httpSession.getAttribute("user")

사용자 A, B 어떻게 구분?


Shell Script function return 문이 어떻게 다른지? 어떻게 풀어야 하는지?


jpa N+1 쓰려면 fetchJoin

fetchJoin하면 쿼리 결과물이 어떻게 되는지?

부모1개, 자식10개 fetchJoin 쓰면 결과물이 몇개가 되는지?

최근에 본 기술책, 아티클, 포스팅, 공식 문서

effective java라고 하면 어떤게 인상 깊었는지. 가장 많이 인용 되는 내용. 챕터.

Reference type과 Primitive type 차이? 책에 있는 내용 알려 달라.

이력서에 따라 다름.


호돌맨.

단방향, 양방향 차이


