= interview

== 자기소개서
https://www.youtube.com/watch?v=pna1BsRF6sI[면접관에게 자기소개서란 2019.07.04]

== 기술면접
https://www.youtube.com/watch?v=QOqUrMzOTcw[면접관이 기술면접에서 보는 것 2019.07.08]

기술면접

면접관 1,2명 이상

1,2시간

회사, 화상

그 동안 경력에 대해. 이력서에 들어가 있는 내용을 가지고 질문.

어떤 일을 했느냐. 설명. 설명 못하면 구라.

내가 하는 일을 얼마나 잘 설명. 코드 몽키였느냐(시키는대로). 개선을 했느냐. 주인의식.

이력서 구멍.
여행? 그때 하고 지금 하고 뭐가 다르냐.

자주 옮겨 다닌 거.
장점이 될 수도 있고 단점이 될 수도 있음.
잘려서 나간 경우. 안 잘리면 버틸지도.
내가 마음에 안들어 나간 경우. 실증 느끼거나 마음에 안들어서 나갈 수도.
단순 노동 시켜서 나왔으면 재미있는거 시켜 주면 안나갈 지도.

면접관. 회사 따라 다름.

학교 별로여도 적어 두는게 좋음. 대학이 최소 요건이면 안적는거 보다 나음.

실제 기술. 5~10분. 이력서에 쓴 기술.
전문가는 전문가라고 말을 잘 못함. 실수 할 수 있음. 실수는 부끄러움.
전문가에 준하는 질문 하면 대답 못하는 경우 많음.
자칭 C#전문가. async, 멀티쓰레드 대답 못하면 꽝.
이 기술 어디 썼고 어떤 문제가 있고.
신 기술 많이 알고 있느냐.
많이 적기만 하면 유행만 따라감.
무슨 차이가 있는지.
현재 나와 있는 기술들 뭐가 나와 있는지. 이해하고 있고. 내부 이해 하면. 다른 기술 나와도 접목.
해 봤는데 좋고 좋고. 못버티고 나감.
약파는거만 배워온 사람.

코딩 시켜 봄.
기본이 되느냐. 스트링 뒤집을 수 있느냐. concat 붙이기 - 기본 없음. 배열로 예쁘게. 기초적인거 까먹으면.
배열. 재귀함수 어떻게 쓰는지
알고리즘.
누구나 알법한 문제를 제대로 풀 수 있느냐.
트리 정도는 범위.
그래프는 암기 수준. 그래프가 필요한 업종 빼고.

스트링 뒤집기 빨리 푸는건 OK. 다른거 빨리 풀면 외운 것일 가능성 높음. 암기 못했을 법한 문제를 냄.
한 번에 푸느냐를 보려는게 아님. 모르겠다고 멘붕해서 다른 문제 하자 그러면 별로. 일하다가도 멘붕 오면?
주먹 구구식으로라도 풀어야 됨.
문제가 명확하지 않은 경우 질문. 이해되지 않습니다면 탈락. 이 문제가 이런 의미인가요? 질문 제대로하고 문제를 풀려고 한다.
어떻게 풀려고 하느냐. 힌트를 주면서. 암시 하는바. 새로운 방향. 막히면 힌트. 발전 시켜 나가는 모습을 보는거.
주어진 정보를 소화해서 최종 결론으로 갈 수 있느냐.
힌트가 적을 수록 잘하는 사람. 힌트 많이 줘도 코치 할 수 있는 사람.
힌트 줘도 자기 세계에 빠져 있는 사람이 있음. 음수 안들어 온다고 힌트 줘도 음수에 빠져 있는 사람이 있음. 옆에서 어떤 지시를 해도 안듣고 자기 고집대로 일함. 같이 일하기 어려움. 시스템 이해 못하고 자기 세상에 빠질 수 있음.

생각하는 능력이 되느냐.
생각 하는 동안 막히면 힌트를 주면 힌트를 이해하고 따라갈 수 있는지.
생각하는 속도가 빠른지. 코드 깔끔한지. 코드 더럽게 짜면 채용 안함.

알고리즘 사이트 달달 외우는 사람. 패스 시켜주는 회사는 프로그래머들이 좋아하는 회사는 아닐 수 있음. 소소하게 돈 받고 일하는 곳. 주인의식. 인정받는 프로그래머 회사는 아닐 수도.

질문할 거 있으면 하라고 함.
그 회사 관심.
기술적인거. 어떤 기술 쓰고. 프로세스 어떤지.

꿀팁. 면접 하다가 코딩 문제 하나 풀었는데 높은 직급 면접관이 일 터졌다고 나가면 안 될 가능성 높음. 면접관 끼리 차고 치는 고스돕일 수 있음.

왜 떨어졌는지 알려 줄 수 있나요. 찾는 사람이 조금 더 높은 사람. 예의상.

내가 기본기가 없는지 절실하게 생각해 봐야됨.

