:hardbreaks:
= airflow

https://airflow.apache.org/

> Airflow is a platform created by the community to programmatically author, schedule and monitor workflows.

Airflow는 워크플로우를 프로그래밍 방식으로 작성, 예약 및 모니터링하기 위해 커뮤니티에서 만든 플랫폼

Airbnb에서 개발함

github: https://github.com/apache/airflow


== Airflow의 장점
* Python을 이용한 유연한 워크플로 정의.
** 파이썬 언어를 이용해서 커스텀 파이프라인 구현 가능.
** 다양한 데이터베이스, 클라우드 서비스 등을 사용할 수 있는 애드온들이 많음
** 다른 워크플로 관리자들은 YAML, JSON, XML 등을 사용하는 경우가 많은데 자유도가 떨어짐
* 점진적(incremental)처리. 전체 파이프라인을 재실행 하지 않고 실패한 부분부터 처리 가능.
* 백필(Backfilling) 기능 제공. 태스크가 며칠 동안 실패된 경우나 새롭게 만든 플로를 과거부터 순차적으로 실행
* 오픈소스
* 웹 인터페이스를 통해 파이프라인 실행 결과를 모니터링하고 오류를 디버깅 하기 좋음

== Airflow가 적합하지 않은 경우
* 스트리밍(실시간데이터 처리)에 적합하지 않음. 반복적이거나 배치 태스크(batch-oriented task)에 적합
* Python을 모르는 경우 어려울 수 있음. 파이프라인 규모가 커지면 복잡해질 수 있음.
* 실행되는 동안 구조 변화가 빈번한 경우

== Airflow 구성 요소
Scheduler, Worker, Webserver, Metadata DB, DAGs, Airflow.cfg 등 다양한 구성요소가 있음

주요 구성요소는 Scheduler, Worker, Webserver

* Airflow Scheduler (스케줄러)
** DAG를 분석하고 현재 시점에서 DAG의 스케줄이 지난 경우 Airflow 워커에 DAG의 태스크를 예약
** 모든 작업(Task)들과 DAG를 모니터링
* Airflow Worker (워커) - 예약된 태스크를 선택하고 실행
* Airflow Webserver (웹 서버) - 스케줄러에서 분석한 DAG를 시각화하고 DAG 실행과 결과를 확인할 수 있는 주요 인터페이스 제공. 파이프라인 태스크 예약하고 모니터링.

Metadata DB
DAGs
Airflow.cfg



== History

2014년 10월 Airbnb에서 시작된 오픈소스 프로젝트
2015년 6월 오픈소스로 공개
2016년 3월 Apache Software Foundation 인큐베이팅
2019년 1월 8일 Apache Top-Level Projection 발표

https://news.apache.org/foundation/entry/the-apache-software-foundation-announces44[THE APACHE SOFTWARE FOUNDATION ANNOUNCES APACHE® AIRFLOW™ AS A TOP-LEVEL PROJECT 2019.01.08]

== 이런저런 정리
crontab, jenkins 처럼 스케줄링을 목적으로 활용하기 좋음

SLA



== DAG (Directed Acyclic Graph) 방향성 비순환 그래프

그래프는 화살표 방향성의 끝점(directed edge)을 포함하되 반복이나 순환을 허용하지 않음 (비순환 acyclic)

반복이나 순환하게 되면 그래프가 동작하지 않음

== 백필(Backfilling)

하나의 플로(Airflow에서는 DAG)를 특정 옵션(기간) 기준으로 다시 실행할 수 있는 기능

태스크가 며칠 동안 실패하거나 새롭게 만든 플로를 과거의 특정 시점부터 순차적으로 실행



== 참고

Apache Airflow 기반의 데이터 파이프라인
에어플로 중심의 워크플로 구축에서 커스텀 컴포넌트 개발및 배포, 관리까지
바스 하렌슬락, 율리안 더라위터르 지음 | 김정민 옮김
제이펍

https://github.com/K9Ns/data-pipelines-with-apache-airflow
https://www.manning.com/books/data-pipelines-with-apache-airflow

(워크플로우관리도구) Airflow 튜토리얼 #1 - Overview 2021.07.20
https://tech.ktcloud.com/72



How To Set SLA in Apache Airflow 2022.07.24
https://senthilnayagan.com/orchestration/2022/airflow-setting-sla

Airflow — Service Level Agreement (SLA) 2019.10.22
https://blog.clairvoyantsoft.com/airflow-service-level-agreement-sla-2f3c91cd84cc
