= 이것이 자바다 - 6.15 어노테이션

== 이것이 자바다 - 6.15 어노테이션(1) 2019.03.22

* https://www.youtube.com/watch?v=zNmq-qGzsUY[이것이 자바다 - 6.15 어노테이션(1) 2019.03.22]

.어노테이션(Annotation)이란
* 프로그램에게 추가적인 정보를 제공해주는 메타데이터(metadata)이다.
* 어노테이션 용도
** 컴파일러에게 코드 작성 문법 에럴르 체크하도록 정보를 제공
*** 예: 메소드가 재정의 되었는지 확인할 수 있다. (@Override)
** 소프트웨어 개발 툴이 빌드나 배치시 코드를 자동으로 생성할 수 있도록 정보를 제공
*** 예: XML 설정 파일을 자동 생성하거나 배포를 위한 JAR 압축 파일을 자동 생성할 수 있다.
** 실행시(런타임시) 특정 기능을 실행하도록 정보를 제공
*** 예: 객체가 애플리케이션 내부에서 해야할 역할을 정의할 수 있다. (서블릿, 컨트롤러, ...)

java5부터 나옴

.어노테이션 타입 정의와 적용
* 어노테이션 타입 정의
** 소스 파일 생성: AnnotationName.java
** 소스 파일 내용
----
public @interface AnnotationName {
}
----
* 어노테이션 타입 적용
----
@AnnotationName
----

----
@Override
public void toString() { ... }
----

.어노테이션의 엘리먼트(element) 멤버
* 어노테이션을 코드에 적용할 떄 외부의 값을 입력받을 수 있도록 하는 역할
* 엘리먼트 선언
----
public @interface AnnotationName {
  타입 elementname() [default 값];
...
----

엘리먼트의 타입은 기본타입과 참조타입을 모두 사용할 수 있다.
----
public @interface AnnotationName {
  String elementName1();
  int elementName2() default 5;
}
----

* 어노테이션 적용시 엘리먼트값을 지정하는 방법
----
@AnnotationName(elementName1="값", elementName2=3);
또는
@AnnotationName(elementName1="값");
----

----
@Controller(name="main")
public class MainController { ... }
----

.기본 엘리먼트 value
----
public @interface AnnotationName {
  String value(); // 기본 엘리먼트 선언
  int elementName() default 5;
}
----

* 어노테이션을 적용할 떄 엘리먼트명을 생략가능
----
@AnnotationName("값");
----

----
@WebServlet("/main")
public class MainServlet { ... }
----

----
@WebServlet(value="/main")
public class MainServlet { ... }
----

* 두 개 이상의 속성을 기술할 떄에는 value=값 형태로 기술
----
@AnnotationName(value="값", elementName=3);
----

.어노테이션 적용 대상
* 코드 상에서 어노테이션을 적용할 수 있는 대상
* java.lang.annotation.ElementType 열거 상수로 정의되어 있음

.Element 열거 상수, 적용 대상
* TYPE - 클래스, 인터페이스, 열거 타입
* ANNOTATION_TYPE - 어노테이션
* FIELD - 필드
* CONSTRUCTOR - 생성자
* METHOD - 메소드
* LOCAL_VARIABLE - 로컬 변수
* PACKAGE - 패키지

.어노테이션 적용 대상 지정 방법
* @Target 어노테이션으로 적용 대상 지정
* @Target의 기본 엘ㄹ먼트인 value의 타입은 ElementType 배열

----
@Target({ElementType.TYPE, ElementType.FIELD, ElementType.METHOD})
public @interface AnnotationName {
}
----

----
@AnnotationName // Type
public class @ClassName {
  @AnnotationName // Field
  private String fieldName;

  // @AnnotationName (X) - 생성자(CONSTRUCTOR)는 선언하지 않았음
  public ClassName() { }

  @AnnotationName // Method
  public void methodName() { }
}
----

.어노테이션 유지 정책
* 어노테이션 적용 코드가 유지되는 시점을 지정하는 것
* java.lang.annotation.RetentionPolicy 열거 상수로 정의되어 있음

RetentionPolicy 열거 상수 - 설명
* SOURCE - 소스상에서만 어노테이션 정보를 유지한다. 소스 코드를 분석할때만 의미가 있으며, 바이트 코드 파일에는 정보가 남지 않는다.
* CLASS - 바이트 코드 파일까지 어노테이션 정보를 유지한다. 하지만 리플렉션을 이용해서 어노테이션 정보를 얻을 수는 없다.
* RUNTIME - 바이트 코드 파일까지 어노테이션 정보를 유지하면서 리플렉션을 이용해서 런타임에 어노테이션 정보를 얻을 수 있다.

* 리플렉션(Reflection): 런타임에 클래스의 메타 정보를 얻는 기능
** 클래스가 가지고 있는 필드, 생성자, 메소드, 어노테이션의 정보를 얻을 수 있다.
** 런타임시에 어노테이션 정보를 얻으려면 유지 정책을 RUNTIME으로 설정해야함.

.유지 정책 지정 방법
* @Retention 어노테이션으로 유지 정책을 지정
* @Retension의 기본 엘리먼트인 value의 타입은 RetentionPolicy

----
@Target({ElementType.TYPE, ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface AnnotationName {
}
----


== 이것이 자바다 - 6.15 어노테이션(2) 2019.03.22

* https://www.youtube.com/watch?v=ZmB9LCf6jaw[이것이 자바다 - 6.15 어노테이션(2) 2019.03.22]

.런타임시에 어노테이션 정보 사용하기
* 클래스에 적용된 어노테이션 정보 얻기
** 클래스.class의 어노테이션 정보를 얻는 메소드를 이용
* 필드, 생성자, 메소드에 적용된 어노테이션 정보 얻기
** 클래스.class의 다음 메소드를 이용해서
** java.lang.reflect 패키지의 Field, Constructor, Method 클래스의 배열을 얻어냄

리턴타입 - 메소드명(매개변수) - 설명
Field[] - getFields() - 필드 정보를 Field 배열로 리턴
Constructor[] - getConstructors() - 생성자 정보를 Constructor 배열로 리턴
Method[] - getDeclaredMethods() - 메소드 정보를 Method 배열로 리턴
** Field, Constructor, Method의 어노테이션 정보를 얻는 메소드를 이용

* 어노테이션 정보를 얻기 위한 메소드
** 뒤 페이지에 있음


