= 우아한형제들 조직문화

https://www.woowahan.com/#/company/culture[우아한문화]

송파구에서 일을 더 잘하는 11가지 방법

.1. 12시 1분은 12시가 아니다.
약속을 지키자

.2. 실행은 수직적! 문화는 수평적~
일을 할 때는 목표를 달성하기 위해 일사불란하게 움직여야 함.
'결정하는 사람'이란 결과에 책임을 질 수 있는 사람
결정한 사람을 중심으로 성과를 달성하기 위해 일사불란하게 움직여야 함.
하지만 인간적인 관계에서는 권위주의를 탈피해야 함. 권위주의는 구성원 개개인의 창의성과 자존감을 손상시킴.

상급자는 본인이 나타났을 때 구성원들 사이에서 어색한 분위기가 형성된다면 스스로를 돌아봐야 함.

.3. 잡담을 많이 나누는 것이 경쟁력이다.
잡담은 신뢰를 만들어가는 원료.

.4. 쓰레기는 먼저 본 사람이 줍는다.

자신의 업무를 넘어서 참여하고 봉사하고 헌신해 건강하고 강한 공동체가 되도록 힘써야 함. (단순히 프로젝트의 성과를 위해서만 일을 한다면 프리랜서나 외주업체 인력의 도움을 받는 것이 나을 수도 있습니다.)

.5. 휴가나 퇴근시 눈치주는 농담을 하지 않는다.

.6. 보고는 팩트에 기반한다.
보고받는 사람들이 선입견이 없도록 우선 팩트에 기반한 보고를 한 후, 자신의 의견과 견해임을 구분해서 밝히고 덧부여 이야기해야 합니다.

"본 것을 본 대로 보고하라, 들은 것을 들은 대로 보고하라! 본 것과 들은 것을 구분해 보고하고, 보지 않고 듣지 않은 것은 절대 이야기하지 말라!" - 이순신 장군 -

.7. 일의 목적, 기간, 결과 공유자를 고민하며 일한다.
일을 할 때는 반드시 그 일의 목적을 생각해야 합니다. 특히 일을 하는 중간중간에도 그 목적을 상기하는 것이 중요합니다. 또한 완료 시점을 고려하며 시간을 잘 활용해야 합니다.

일의 결과는 처음 서로 예상하고 기대한 것과 어긋나지는 않는지 점검하고, 일을 마무리하기 전 이 일로 영향을 받을 사람들에게 제때 공유합니다. 공유할 때는 단순 전달이 아닌 상대방이 명확히 이해했는지까지 확인해야 합니다.

.8. 책임은 실행한 사람이 아닌 결정한 사람이 진다.
우리가 하는 일은, 많은 경우 실패할 확률이 큽니다. 중요한 것은 실패를 통해 계속 배워나가고, 조직과 프로세스를 정비해 나가는 것입니다.

결정한 사람은 실행하는 사람이 성공할 수 있도록 지속적인 관심과 도움을 주어야 하며, 혹여 실패했을 경우 실행자들이 용기를 잃지 않도록 격려하고, 또 그 실패가 잘못된 결정으로 인한 것이라면 그에 대해 사과해야 합니다. 다만 실행자들의 불성실함과 비도덕적인 행동으로 일이 실패했을 경우에는 그 책임을 엄중하게 물어야 합니다.

.9. 가족에게 부끄러운 일은 하지 않는다.
우리는 회사의 구성원이기 이전에 성숙한 시민으로서 법규를 준수하고 도덕적인 가치를 소중히 여깁니다.

누군가에게 설명할 수 없는 일은 하지 않으며, 가족, 특히 자녀에게 양심적으로 떳떳할 수 있도록 행동해야합니다. 도덕성을 희생하며 성과를 얻는 것은 차라리 손해를 보는 것보돠 못합니다.

.10. 모든 일의 궁극적인 목적은 '고객창출'과 '고객만족'이다.
고객 없이는 회사는 존재할 수 없습니다. 회사가 학교, 병원, 종교집단, 군대 등 다른 조직과 구분되는 가장 큰 지점은 바로 '고객'에 있습니다. 회사에서 내려야 하는 모든 의사결정은 고객을 중심으로 접근해야 합니다.
의사결정을 할 때 고객을 배제하고 회사간, 부서 간의 정치적인 상황을 고려해 타협하는 것은 바보같은 행위입니다.

회사의 목적은 '이익 창출'이 아닌 '고객 창출'이며 이를 우선한 결정을 통해서만 지속가능한 성장을 도모할 수 있습니다.

.11. 이끌거나, 따르거나, 떠나거나!
일의 성공에는 리더십도 중요하지만 그것만큼 팔로워십도 중요합니다. 오류가 없는 결정은 있을 수 없습니다. 하지만 잘못된 결정에 따른 실행도 아예 실행하지 않는 것보다는 낫습니다.

리더십을 발휘하는 사람은 복수의 구성원이 동일한 의견을 제시할 경우 토론을 통해 계획을 수정해 나갑니다. 팔로워십을 발휘하는 사람은 개인의 편의와 이익이 아닌 프로젝트의 성공, 고객의 이익을 중심으로 의견을 제시해야 합니다. 건전한 비판과 토론이 아닌 냉소와 방관하는 자신의 모습이 보인다면 본인과 주변 구성원 모두를 위해 회사를 떠날 때입니다.

