:hardbreaks:
= 전세보증보험

== 주택도시보증공사 전세보증금반환보증
https://www.khug.or.kr/hug/web/ig/dr/igdr000001.jsp



== References
* https://www.youtube.com/watch?v=YELuU8G0YBY[모르면 당한다구요! 전세계약 주의사항 4가지ㅣ깡통전세 예방법 l 2019.09.02]

깡동전세 경매 넘어가서 1억 날린 경험이 있음.

역전세: 매매가가 전세가 이하로 떨어져서 전세가가 역전
집주인이 돌려주면 다행인데 갭투자 한다면
경매, 집주인 파산, 내 보증금도 날아감

깡통전세 예방 4가지 방법
1. 보증금과 근저당이 매매가의 70% 넘지 않는다. 보증금이 KB시세의 70% 넘지 않도록. 경매에 유찰되면 20%, 30%씩 떨어짐. 최소 한 번 이상 유찰되는편
2. 잔금 치르는 날 [전입신고+확정일자]는 반드시 받는다. 잔금 치르기 직전 최종적으로 등기부등본을 한 번 더 떼서 그 사이에 바뀐 사항 없는지. 집주인이 새로 받은 대출 없는지 확인. 계약 하자 마자 전입신고+확정일자. 집주인이 그 전에 대출 받으면 후순위가 되어 버림. 전입신고 다음 날 0시부터 세입자의 대항력 발생. 최종 낙찰자가 보증금까지 다 물어주도록 되어 있음. 전입신고 안하는 조건으로 하다가 당했음. 잔금치르는 날 이사보다 전입신고+확정일자가 중요.
3. 전세권 설정하기. 등기부에 전세권을 설정하는 것. 집주인이 안해주는 편. 경매 넘어가면 알려주는 권리. 집주인이 보증금 안돌려 주면 전세권 가진 세입자가 경매에 넘길 수 있음. 집주인이 전세권 설정해 주면 하면 됨.
4. 전세금 반환 보증보험 활용. 근저당이 애매하게 잡혀 있다. 불안하다. 집주인 동의없이 가입할 수 있음. 보증기간이 보증. 임대차 계약이 만료되고 30일이 지났는데도 특별한 이유 없이 집주인이 전세보증금 돌려주지 않거나 경매나 공매로 넘어가가고 낙찰 받고 배당 다 되었는데도 돌려받지 못한 경우 내 보증금 대신 반환해줌. 주택도시공사 HUG, SGI서울보증 두 군데. 임대차 계약을 맺고 최대 1년이 넘어가기 전에 가입 가능. SGI서울보증은 10개월, HUG는 1년 이내. 보증금 한도. 서울보증보험 아파트 무제한, HUG 수도건 7억 이하. 액수가 크면 서울보증보험. 보험료는 보통  전세가의 0.2% 내외. 아파트가 가장 저렴한 편. 그 외 주택은 보험료율이 좀 더 높음. 신혼부부, 다자녀, 저소득층은 40% 할인. 1년 기준. 2년 하면 2년치.


* https://www.youtube.com/watch?v=2GqyK5HlCY8[전세보증보험 가입해도 문제 생길 수 있어요 2020.10.11]

SGI서울보증 - 전세금보장신용보험
HUG 주택도시보증공사 -
HF 한국주택금융공사

전셋집이 경매로 넘어갈 때 보증금을 돌려받을 수 있다

보증금액
SGI
HUG - 수도권 전세보증금 7억 이하
HF - 수도권 전세보증금 5억 이하
https://www.hf.go.kr/hf/sub02/sub12_01.do[전세지킴보증]

보증료율
SGI 0.192%
HUG 0.128%
HF 0.07%
https://www.hf.go.kr/hf/sub02/sub12_01.do#/jwxe_main_content
홈페이지에 기준 보증료율이 연 0.04%라고 나오는데


보증신청기간
SGI 임대차 계약 기간이 1년이면 5개월 전. 계약 기간이 1년 넘으면 10개월 전.
HUG 잔금지급일과 전입신고일 중 늦은 날 ~ 전세계약기간의 2분의 1이 경과 하기 전
HF 4분의 1 경과 하기 전

보증료 할인
SGI
HUG LTV 80%~70% 10%, 70~60% 20%, 60% 이하 30%

가입 구비 서류
SGI
HUG - 임차인의 주민등록등(초)본, 임차목적물의 등기부등본(전입신고 이후 발급분), 전입세대열람원, 확정일자부 임대차계약서
HF

=== 확인할 거

전세보증보험 가입에 걸리는 시간?
전세보증보험 안되는 케이스?
보험료율?
전입신고 확정일자 받은 날 집주인이 대출을 받았는지 어떻게 알 수 있나?
다음날 0시부터 효력이 발생하는데?
집주인이 설정한 근저당권은 당일 즉시 효력이 발생하는데?
