:hardbreaks:
= mysql - autoReconnect

DB에 접속중인 세션을 오랫동안 사용하지 않다가 다시 사용하려고 하면, 다음과 같은 메시지를 보게 된다.
----
The last packet successfully received from the server was 1,155,390,325 milliseconds ago. The last packet sent successfully to the server was 1,155,390,325 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
----
MySQL 서버의 wait_timeout 설정을 늘려줄 수도 있겠지만 서버 설정을 고치기 어려운 경우가 많다. 그리고 불필요한 커넥션을 오랬동안 유지하고 있는 것도 자원의 낭비이다.

다른 방법으로 autoReconnect 옵션을 사용할 수 있다. autoReconnect 옵션은 커넥션이 끊어졌을 때 자동으로 재접속을 시도한다. 하지만 이 옵션을 사용하면 커넥션이 끊어졌을 때 다음과 같은 문제가 발생할 수 있다.

SQLException 예외처리를 제대로 하지 않으면 다음과 같은 문제가 발생할 수 있다. 첫번째 쿼리가 수행 된 다음 커넥션이 끊어 졌을 때 첫번째 쿼리는 롤백 되었는데, 두번째 세번째 쿼리가 수행되고 커밋 될 수 있는 것이다.




== References
* https://blog-han.tistory.com/40[[버그해결\]MySQL , Maria DB Connection을 잃어버리는 문제 해결 2019.03.27]

autoReconnect=true
validationQuery="select 1"

https://blog.naver.com/seuis398/70118975290[JDBC autoReconnect=true 옵션 사용시 유의사항 2011.09.18]

autoReconnect 옵션은 쿼리를 수행한 다음 DB 세션에 문제가 있으면 단순히 SQLException 리턴 후 재접속 처리를 한다.
문제는 트랜잭션 구동 환경에서 수행중이던 트랜잭션은 롤백이 되어야 하고, 남은 트랜잭션은 수행이 되지 않아야 되는데, autoReconnect 옵션은 이런 처리를 해주지 않기 때문이다.



트랜잭션을 사용하는 환경이라면 DB 세션의 재접속 처리는 JDBC의 autoReconnect 설정이 아닌 DBCP의 validationQuery 기능을 사용하는 것이 적합하다.


https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-high-availability-and-clustering.html[6.3.12 High Availability and Clustering]



https://kshmc.tistory.com/entry/MyBatis-Datasource-%EC%B0%B8%EA%B3%A0[[MyBATIS(MySQL)\] JDBC autoReconnect=true 옵션 사용시 유의사항 2015.01.23]
