:hardbreaks:
= 아키텍처


== References
* https://www.youtube.com/watch?v=Ql7CoQminoM[누누, 다즐의 클린 아키텍처 2023.09.29]

다룰 내용
1. 소프트웨어 아키텍처란
2. 레이어드 아키텍처
3. 클린 아키텍처
4. 헥사고날 아키텍처
5. 마치며

아키텍처?
어떤 대상의 구성과 동작 원리, 구성 요소간의 관계 및 시스템 외부 환경과의 관계를 설명하는 하나의 설명서

소프트웨어 아키텍처
소프트웨어 구성요소들 사이 관계를 표현

소프트웨어가 제공하는 가치
기능, 구조

보통 기능에 집중

구조가 더 중요
로버트 마틴은 구조가 더 중요하다고 함

비유를 들어 설명
방은 구조가 되고 물건은 기능
아무렇게나 배치하면 물건을 놓다 보면 방이 꽉 참
물건을 찾기 어려움
물건을 추가로 넣을 공간이 없음
기능은 많지만 복잡한 구조

구조를 잡고 물건을 넣으면 새로운 물건을 넣기도 좋음

왜 구조가 중요할까
소프트웨어 비용과 관련

기능을 개발하는 비용보다 유지보수 하는 비용이 더 크다

기능 좋은 + 구조 부족
* 당장은 좋다
* 하지만 수정 비용이 너무 크다
* 언제 버려질지 모른다

기능 부족 + 구조 좋음
* 당장은 부족
* 수정하는데 비용이 적다
* 개선, 확장에 유연하다

좋은 구조를 만드는 방법
* 패러다임
* 설계 원칙 (SOLID)
* 응집 원칙
* 결합 원칙

모든 것을 지키면서 개발하기 어렵다!

아키텍처 패턴
* 계층형 아키텍처
* 클린 아키텍처
* 헥사고날 아키텍처

원칙을 지킬 수 있도록 도와준다!

아키텍처 적용
핵심요소인 도메인을 지킬 수 있음
외부요소인 UI, DB, ... 도메인에 의존하지 않도록

레이어드 아키텍처
관심사가 같은 코드들을 계층으로 그룹화

Client -> Presentation Layer -> Application Layer -> Persistence Layer


레이어드 아키텍처 특징
1. 계층화로 인한 분리된 책임
2. 편의에 따라 여러 계층을 추가 가능하다
e.g. presentation, application, domain, persistence
3. 구조가 쉽고 단순하고 익숙하다
4. 데이터베이스 주도 설계가 될 수 있다


Client --요청--> Presentation Layer --처리요청--> Application Layer --데이터 요청--> Persistence Layer

Persistence Layer --데이터 응답--> Application Layer --처리 응답--> Presentation Layer --응답--> Client

상위 레이어가 하위 레이어를 알 수 있다

변경의 영향을 준다

의존성이 생겼다고 할 수 있음

한 계층의 변화가 다른 계층의 변화를 준다

Persistence 변화가 Application 변화, Presentation 까지 영향을 줌

테스트도 쉽지 않음

데이터와 함께 테스트해야 되는 상황이 발생

DB 구조가 이상해서 DB를 바꾸려고 하는데 이거 해도 되나요?


클린 아키텍처
의존성 역전을 통해 도메인이 중심

의존성 방향이 안쪽으로만 향한다

클린 아키텍처 특징
1. 핵심 규칙을 담고 있는 도메인이 중심
2. 도메인이 세부 사항에 의존하지 않는다
3. 익숙하지 않을 수 있고 레퍼런스가 적다

세부사항
입출력 장비, 디비, 웹시스템, 서버, 프레임워크, 통신 프로토콜 등이 있음

Entity와 Use Cases가 있는 계층
외부 요소에 대해서는 절대로 알면 안됨

두번째 요소는 외부요소가 있는 계층. 어떤 DB, 어떤 프레임워크

이 두가지 부분을 분리하는 것이 핵심


클린아키텍처는 총 4개의 레이어로 구성

* Enterprise Business Rules
* Application Business Rules
* Interface Adapters
* Frameworks & Drivers

1. 엔터프라이즈 비즈니스 규칙 (Entities)
: 애플리케이션의 핵심적인 엔티티나 도메인 객체를 의미

비즈니스 로직이나 규칙을 나타내며, 외부 요소에 대한 어떠한 의존성도 X

대부분의 프로젝트에서 도메인 패키지에 들어있는 것들

Entity 레이어
가장 핵심적인 비즈니스...

2. 애플리케이션 비즈니스 규칙 (Use Cases)
: 특정 비즈니스 로직을 포함하며 데이터 저장, UI 등은 관심 없다

Use Cases 레이어


3. 인터페이스 어댑터 (Interface Adapters)
: 데이터 애플리케이션에서 사용하는 형태로 변환하거나, 내부에서 사용하는 데이터를 ...

4. 외부 요소 (Frameworks & Drivers)
특정 프레임워크나 기술에 의존하는 부분을 의미

인프라스트럭처 레이어


클린 아키텍처는 추상적이다
지침도 존재하지 않는다


헥사고날 아키텍처

외부 요소와

포트를 통해서 접근

헥사고날 아키텍처 특징
1. 큰 비즈니스 가치를 가지고 있는 도메인 모델에 큰 관심
2. 레퍼런스가 클린 아키텍처에 비해 많다
3. 포트와 어댑터를 구성하고 관리하는데 복잡성이 따른다
4. 도메인에 라이브러리를 직접 활용하기 어렵다

도메인 모델 (Domain Model)

애플리케이션의 핵심 기능, ..

포트 (Port)
애플리케이션의 도메인 모델과 외부의 통신 인터페이스를 정의

어댑터 (Adapter)
특정 포트에 연결되어 외부와 도메인간 통신을 가능하게 한다.
= 외부 요소 (웹 요청, 데이터베이스)...

입력 포트 & 어댑터
입력포트는 동작을 유발하는 외부 요청을 처리
출력포트는 동작의 결과를 외부로 전달

프레젠테이션, 도메인, 영속성
프레젠테이션: View -> Controller ->

도메인: Use Case -> Entity

영속성: RepositoryImpl <- Data Source

헥사고날 아키텍처 어떻게 적용할까

서비스와 레포지토리의 메서드를 인터페이스로 추출하는 것


이럴 때 고려해보세요
1. 대규모 프로젝트를 진행할 때
2. 프로젝트 일원 모두 클린 아키텍처를 이해하고 있을 떄
3. 외부 요소의 변화가 잦을 때

참고
- 만들면서 배우는 클린 아키텍처
- ...

https://www.youtube.com/watch?v=g6Tg6_qpIVc[클린 아키텍처 애매한 부분 정해 드립니다. 2023.01.04]


